/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AiConfigDto
    /// </summary>
    [DataContract(Name = "AiConfigDto")]
    public partial class AiConfigDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AiConfigDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AiConfigDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AiConfigDto" /> class.
        /// </summary>
        /// <param name="autoReply">autoReply.</param>
        /// <param name="maxToolCalls">maxToolCalls.</param>
        /// <param name="model">model (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="provider">provider (required).</param>
        /// <param name="systemPrompt">systemPrompt.</param>
        /// <param name="triggerOn">triggerOn.</param>
        public AiConfigDto(bool? autoReply = default, int? maxToolCalls = default, string model = default, string name = default, string provider = default, string systemPrompt = default, List<string> triggerOn = default)
        {
            // to ensure "model" is required (not null)
            if (model == null)
            {
                throw new ArgumentNullException("model is a required property for AiConfigDto and cannot be null");
            }
            this.Model = model;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for AiConfigDto and cannot be null");
            }
            this.Name = name;
            // to ensure "provider" is required (not null)
            if (provider == null)
            {
                throw new ArgumentNullException("provider is a required property for AiConfigDto and cannot be null");
            }
            this.Provider = provider;
            this.AutoReply = autoReply;
            this.MaxToolCalls = maxToolCalls;
            this.SystemPrompt = systemPrompt;
            this.TriggerOn = triggerOn;
        }

        /// <summary>
        /// Gets or Sets AutoReply
        /// </summary>
        [DataMember(Name = "auto_reply", EmitDefaultValue = true)]
        public bool? AutoReply { get; set; }

        /// <summary>
        /// Gets or Sets MaxToolCalls
        /// </summary>
        [DataMember(Name = "max_tool_calls", EmitDefaultValue = true)]
        public int? MaxToolCalls { get; set; }

        /// <summary>
        /// Gets or Sets Model
        /// </summary>
        [DataMember(Name = "model", IsRequired = true, EmitDefaultValue = true)]
        public string Model { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        [DataMember(Name = "provider", IsRequired = true, EmitDefaultValue = true)]
        public string Provider { get; set; }

        /// <summary>
        /// Gets or Sets SystemPrompt
        /// </summary>
        [DataMember(Name = "system_prompt", EmitDefaultValue = true)]
        public string SystemPrompt { get; set; }

        /// <summary>
        /// Gets or Sets TriggerOn
        /// </summary>
        [DataMember(Name = "trigger_on", EmitDefaultValue = true)]
        public List<string> TriggerOn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AiConfigDto {\n");
            sb.Append("  AutoReply: ").Append(AutoReply).Append("\n");
            sb.Append("  MaxToolCalls: ").Append(MaxToolCalls).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  SystemPrompt: ").Append(SystemPrompt).Append("\n");
            sb.Append("  TriggerOn: ").Append(TriggerOn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
