/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AnlageGErgebnis
    /// </summary>
    [DataContract(Name = "AnlageGErgebnis")]
    public partial class AnlageGErgebnis : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnlageGErgebnis" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AnlageGErgebnis() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AnlageGErgebnis" /> class.
        /// </summary>
        /// <param name="gewinnVerlust">gewinnVerlust (required).</param>
        /// <param name="gewstGezahlt">gewstGezahlt (required).</param>
        /// <param name="gewstMessbetragApprox">gewstMessbetragApprox (required).</param>
        /// <param name="gewstPflichtig">gewstPflichtig (required).</param>
        /// <param name="jahr">jahr (required).</param>
        /// <param name="kfzHinweise">kfzHinweise (required).</param>
        public AnlageGErgebnis(string gewinnVerlust = default, string gewstGezahlt = default, string gewstMessbetragApprox = default, bool gewstPflichtig = default, int jahr = default, List<AnlageGKfzHinweis> kfzHinweise = default)
        {
            // to ensure "gewinnVerlust" is required (not null)
            if (gewinnVerlust == null)
            {
                throw new ArgumentNullException("gewinnVerlust is a required property for AnlageGErgebnis and cannot be null");
            }
            this.GewinnVerlust = gewinnVerlust;
            // to ensure "gewstGezahlt" is required (not null)
            if (gewstGezahlt == null)
            {
                throw new ArgumentNullException("gewstGezahlt is a required property for AnlageGErgebnis and cannot be null");
            }
            this.GewstGezahlt = gewstGezahlt;
            // to ensure "gewstMessbetragApprox" is required (not null)
            if (gewstMessbetragApprox == null)
            {
                throw new ArgumentNullException("gewstMessbetragApprox is a required property for AnlageGErgebnis and cannot be null");
            }
            this.GewstMessbetragApprox = gewstMessbetragApprox;
            this.GewstPflichtig = gewstPflichtig;
            this.Jahr = jahr;
            // to ensure "kfzHinweise" is required (not null)
            if (kfzHinweise == null)
            {
                throw new ArgumentNullException("kfzHinweise is a required property for AnlageGErgebnis and cannot be null");
            }
            this.KfzHinweise = kfzHinweise;
        }

        /// <summary>
        /// Gets or Sets GewinnVerlust
        /// </summary>
        [DataMember(Name = "gewinn_verlust", IsRequired = true, EmitDefaultValue = true)]
        public string GewinnVerlust { get; set; }

        /// <summary>
        /// Gets or Sets GewstGezahlt
        /// </summary>
        [DataMember(Name = "gewst_gezahlt", IsRequired = true, EmitDefaultValue = true)]
        public string GewstGezahlt { get; set; }

        /// <summary>
        /// Gets or Sets GewstMessbetragApprox
        /// </summary>
        [DataMember(Name = "gewst_messbetrag_approx", IsRequired = true, EmitDefaultValue = true)]
        public string GewstMessbetragApprox { get; set; }

        /// <summary>
        /// Gets or Sets GewstPflichtig
        /// </summary>
        [DataMember(Name = "gewst_pflichtig", IsRequired = true, EmitDefaultValue = true)]
        public bool GewstPflichtig { get; set; }

        /// <summary>
        /// Gets or Sets Jahr
        /// </summary>
        [DataMember(Name = "jahr", IsRequired = true, EmitDefaultValue = true)]
        public int Jahr { get; set; }

        /// <summary>
        /// Gets or Sets KfzHinweise
        /// </summary>
        [DataMember(Name = "kfz_hinweise", IsRequired = true, EmitDefaultValue = true)]
        public List<AnlageGKfzHinweis> KfzHinweise { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnlageGErgebnis {\n");
            sb.Append("  GewinnVerlust: ").Append(GewinnVerlust).Append("\n");
            sb.Append("  GewstGezahlt: ").Append(GewstGezahlt).Append("\n");
            sb.Append("  GewstMessbetragApprox: ").Append(GewstMessbetragApprox).Append("\n");
            sb.Append("  GewstPflichtig: ").Append(GewstPflichtig).Append("\n");
            sb.Append("  Jahr: ").Append(Jahr).Append("\n");
            sb.Append("  KfzHinweise: ").Append(KfzHinweise).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
