/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CategoryTotal
    /// </summary>
    [DataContract(Name = "CategoryTotal")]
    public partial class CategoryTotal : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CategoryTotal" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CategoryTotal() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CategoryTotal" /> class.
        /// </summary>
        /// <param name="categoryId">categoryId (required).</param>
        /// <param name="sharePct">sharePct (required).</param>
        /// <param name="tco2e">tco2e (required).</param>
        public CategoryTotal(string categoryId = default, double sharePct = default, string tco2e = default)
        {
            // to ensure "categoryId" is required (not null)
            if (categoryId == null)
            {
                throw new ArgumentNullException("categoryId is a required property for CategoryTotal and cannot be null");
            }
            this.CategoryId = categoryId;
            this.SharePct = sharePct;
            // to ensure "tco2e" is required (not null)
            if (tco2e == null)
            {
                throw new ArgumentNullException("tco2e is a required property for CategoryTotal and cannot be null");
            }
            this.Tco2e = tco2e;
        }

        /// <summary>
        /// Gets or Sets CategoryId
        /// </summary>
        [DataMember(Name = "category_id", IsRequired = true, EmitDefaultValue = true)]
        public string CategoryId { get; set; }

        /// <summary>
        /// Gets or Sets SharePct
        /// </summary>
        [DataMember(Name = "share_pct", IsRequired = true, EmitDefaultValue = true)]
        public double SharePct { get; set; }

        /// <summary>
        /// Gets or Sets Tco2e
        /// </summary>
        [DataMember(Name = "tco2e", IsRequired = true, EmitDefaultValue = true)]
        public string Tco2e { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CategoryTotal {\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  SharePct: ").Append(SharePct).Append("\n");
            sb.Append("  Tco2e: ").Append(Tco2e).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
