/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CustomerCommunicationUpdate
    /// </summary>
    [DataContract(Name = "CustomerCommunicationUpdate")]
    public partial class CustomerCommunicationUpdate : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Channel
        /// </summary>
        [DataMember(Name = "channel", EmitDefaultValue = true)]
        public CommunicationChannel? Channel { get; set; }

        /// <summary>
        /// Gets or Sets Direction
        /// </summary>
        [DataMember(Name = "direction", EmitDefaultValue = true)]
        public CommunicationDirection? Direction { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerCommunicationUpdate" /> class.
        /// </summary>
        /// <param name="body">The message body, call summary or note text..</param>
        /// <param name="channel">channel.</param>
        /// <param name="contactId">The contact (customer/supplier) this communication belongs to. References the contact entity..</param>
        /// <param name="counterparty">Email/phone of the counterparty, if applicable..</param>
        /// <param name="direction">direction.</param>
        /// <param name="occurredAt">When the communication happened (defaults to now on create)..</param>
        /// <param name="subject">subject.</param>
        /// <param name="tags">Free-form tags, e.g. &#x60;[\&quot;follow-up-required\&quot;]&#x60;..</param>
        public CustomerCommunicationUpdate(string body = default, CommunicationChannel? channel = default, string contactId = default, string counterparty = default, CommunicationDirection? direction = default, DateTime? occurredAt = default, string subject = default, Object tags = default)
        {
            this.Body = body;
            this.Channel = channel;
            this.ContactId = contactId;
            this.Counterparty = counterparty;
            this.Direction = direction;
            this.OccurredAt = occurredAt;
            this.Subject = subject;
            this.Tags = tags;
        }

        /// <summary>
        /// The message body, call summary or note text.
        /// </summary>
        /// <value>The message body, call summary or note text.</value>
        [DataMember(Name = "body", EmitDefaultValue = true)]
        public string Body { get; set; }

        /// <summary>
        /// The contact (customer/supplier) this communication belongs to. References the contact entity.
        /// </summary>
        /// <value>The contact (customer/supplier) this communication belongs to. References the contact entity.</value>
        [DataMember(Name = "contactId", EmitDefaultValue = true)]
        public string ContactId { get; set; }

        /// <summary>
        /// Email/phone of the counterparty, if applicable.
        /// </summary>
        /// <value>Email/phone of the counterparty, if applicable.</value>
        [DataMember(Name = "counterparty", EmitDefaultValue = true)]
        public string Counterparty { get; set; }

        /// <summary>
        /// When the communication happened (defaults to now on create).
        /// </summary>
        /// <value>When the communication happened (defaults to now on create).</value>
        [DataMember(Name = "occurredAt", EmitDefaultValue = true)]
        public DateTime? OccurredAt { get; set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [DataMember(Name = "subject", EmitDefaultValue = true)]
        public string Subject { get; set; }

        /// <summary>
        /// Free-form tags, e.g. &#x60;[\&quot;follow-up-required\&quot;]&#x60;.
        /// </summary>
        /// <value>Free-form tags, e.g. &#x60;[\&quot;follow-up-required\&quot;]&#x60;.</value>
        [DataMember(Name = "tags", EmitDefaultValue = true)]
        public Object Tags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomerCommunicationUpdate {\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Channel: ").Append(Channel).Append("\n");
            sb.Append("  ContactId: ").Append(ContactId).Append("\n");
            sb.Append("  Counterparty: ").Append(Counterparty).Append("\n");
            sb.Append("  Direction: ").Append(Direction).Append("\n");
            sb.Append("  OccurredAt: ").Append(OccurredAt).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
