/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CustomerGroup
    /// </summary>
    [DataContract(Name = "CustomerGroup")]
    public partial class CustomerGroup : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerGroup" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CustomerGroup() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerGroup" /> class.
        /// </summary>
        /// <param name="description">description.</param>
        /// <param name="memberIds">Contact ids that are members of this group..</param>
        /// <param name="membershipFilter">Rule description for membership, e.g. \&quot;orders &gt; 5 last 12 months\&quot;..</param>
        /// <param name="name">Unique group name, e.g. \&quot;VIP\&quot;, \&quot;Wholesale\&quot;, \&quot;Newsletter\&quot;. (required).</param>
        public CustomerGroup(string description = default, List<string> memberIds = default, string membershipFilter = default, string name = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CustomerGroup and cannot be null");
            }
            this.Name = name;
            this.Description = description;
            this.MemberIds = memberIds;
            this.MembershipFilter = membershipFilter;
        }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Contact ids that are members of this group.
        /// </summary>
        /// <value>Contact ids that are members of this group.</value>
        [DataMember(Name = "memberIds", EmitDefaultValue = false)]
        public List<string> MemberIds { get; set; }

        /// <summary>
        /// Rule description for membership, e.g. \&quot;orders &gt; 5 last 12 months\&quot;.
        /// </summary>
        /// <value>Rule description for membership, e.g. \&quot;orders &gt; 5 last 12 months\&quot;.</value>
        [DataMember(Name = "membershipFilter", EmitDefaultValue = true)]
        public string MembershipFilter { get; set; }

        /// <summary>
        /// Unique group name, e.g. \&quot;VIP\&quot;, \&quot;Wholesale\&quot;, \&quot;Newsletter\&quot;.
        /// </summary>
        /// <value>Unique group name, e.g. \&quot;VIP\&quot;, \&quot;Wholesale\&quot;, \&quot;Newsletter\&quot;.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomerGroup {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  MemberIds: ").Append(MemberIds).Append("\n");
            sb.Append("  MembershipFilter: ").Append(MembershipFilter).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
