/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Employment type.
    /// </summary>
    /// <value>Employment type.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EmploymentType
    {
        /// <summary>
        /// Enum Fulltime for value: fulltime
        /// </summary>
        [EnumMember(Value = "fulltime")]
        Fulltime = 1,

        /// <summary>
        /// Enum Parttime for value: parttime
        /// </summary>
        [EnumMember(Value = "parttime")]
        Parttime = 2,

        /// <summary>
        /// Enum Contract for value: contract
        /// </summary>
        [EnumMember(Value = "contract")]
        Contract = 3,

        /// <summary>
        /// Enum Internship for value: internship
        /// </summary>
        [EnumMember(Value = "internship")]
        Internship = 4,

        /// <summary>
        /// Enum Temporary for value: temporary
        /// </summary>
        [EnumMember(Value = "temporary")]
        Temporary = 5
    }

}
