/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Job
    /// </summary>
    [DataContract(Name = "Job")]
    public partial class Job : IValidatableObject
    {

        /// <summary>
        /// pending | running | done | failed
        /// </summary>
        /// <value>pending | running | done | failed</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public JobStatus Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Job" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Job() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Job" /> class.
        /// </summary>
        /// <param name="attempts">attempts.</param>
        /// <param name="jobType">Discriminator the worker dispatches on (e.g. \&quot;webhook.deliver\&quot;). (required).</param>
        /// <param name="maxAttempts">maxAttempts (required).</param>
        /// <param name="payload">payload.</param>
        /// <param name="runAt">Earliest execution time; None &#x3D; run now..</param>
        /// <param name="status">pending | running | done | failed (required).</param>
        public Job(int attempts = default, string jobType = default, int maxAttempts = default, Object payload = default, DateTime? runAt = default, JobStatus status = default)
        {
            // to ensure "jobType" is required (not null)
            if (jobType == null)
            {
                throw new ArgumentNullException("jobType is a required property for Job and cannot be null");
            }
            this.JobType = jobType;
            this.MaxAttempts = maxAttempts;
            this.Status = status;
            this.Attempts = attempts;
            this.Payload = payload;
            this.RunAt = runAt;
        }

        /// <summary>
        /// Gets or Sets Attempts
        /// </summary>
        [DataMember(Name = "attempts", EmitDefaultValue = false)]
        public int Attempts { get; set; }

        /// <summary>
        /// Discriminator the worker dispatches on (e.g. \&quot;webhook.deliver\&quot;).
        /// </summary>
        /// <value>Discriminator the worker dispatches on (e.g. \&quot;webhook.deliver\&quot;).</value>
        [DataMember(Name = "jobType", IsRequired = true, EmitDefaultValue = true)]
        public string JobType { get; set; }

        /// <summary>
        /// Gets or Sets MaxAttempts
        /// </summary>
        [DataMember(Name = "maxAttempts", IsRequired = true, EmitDefaultValue = true)]
        public int MaxAttempts { get; set; }

        /// <summary>
        /// Gets or Sets Payload
        /// </summary>
        [DataMember(Name = "payload", EmitDefaultValue = true)]
        public Object Payload { get; set; }

        /// <summary>
        /// Earliest execution time; None &#x3D; run now.
        /// </summary>
        /// <value>Earliest execution time; None &#x3D; run now.</value>
        [DataMember(Name = "runAt", EmitDefaultValue = true)]
        public DateTime? RunAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Job {\n");
            sb.Append("  Attempts: ").Append(Attempts).Append("\n");
            sb.Append("  JobType: ").Append(JobType).Append("\n");
            sb.Append("  MaxAttempts: ").Append(MaxAttempts).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  RunAt: ").Append(RunAt).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
