/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// KonzernThresholds
    /// </summary>
    [DataContract(Name = "KonzernThresholds")]
    public partial class KonzernThresholds : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KonzernThresholds" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KonzernThresholds() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KonzernThresholds" /> class.
        /// </summary>
        /// <param name="bilanzsumme">bilanzsumme (required).</param>
        /// <param name="mitarbeiter">mitarbeiter (required).</param>
        /// <param name="nettoUmsatz">nettoUmsatz (required).</param>
        public KonzernThresholds(string bilanzsumme = default, long mitarbeiter = default, string nettoUmsatz = default)
        {
            // to ensure "bilanzsumme" is required (not null)
            if (bilanzsumme == null)
            {
                throw new ArgumentNullException("bilanzsumme is a required property for KonzernThresholds and cannot be null");
            }
            this.Bilanzsumme = bilanzsumme;
            this.Mitarbeiter = mitarbeiter;
            // to ensure "nettoUmsatz" is required (not null)
            if (nettoUmsatz == null)
            {
                throw new ArgumentNullException("nettoUmsatz is a required property for KonzernThresholds and cannot be null");
            }
            this.NettoUmsatz = nettoUmsatz;
        }

        /// <summary>
        /// Gets or Sets Bilanzsumme
        /// </summary>
        [DataMember(Name = "bilanzsumme", IsRequired = true, EmitDefaultValue = true)]
        public string Bilanzsumme { get; set; }

        /// <summary>
        /// Gets or Sets Mitarbeiter
        /// </summary>
        [DataMember(Name = "mitarbeiter", IsRequired = true, EmitDefaultValue = true)]
        public long Mitarbeiter { get; set; }

        /// <summary>
        /// Gets or Sets NettoUmsatz
        /// </summary>
        [DataMember(Name = "netto_umsatz", IsRequired = true, EmitDefaultValue = true)]
        public string NettoUmsatz { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KonzernThresholds {\n");
            sb.Append("  Bilanzsumme: ").Append(Bilanzsumme).Append("\n");
            sb.Append("  Mitarbeiter: ").Append(Mitarbeiter).Append("\n");
            sb.Append("  NettoUmsatz: ").Append(NettoUmsatz).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
