/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PackingQueueItem
    /// </summary>
    [DataContract(Name = "PackingQueueItem")]
    public partial class PackingQueueItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PackingQueueItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PackingQueueItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PackingQueueItem" /> class.
        /// </summary>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="customerId">customerId (required).</param>
        /// <param name="deliveryNotePrinted">deliveryNotePrinted (required).</param>
        /// <param name="items">items (required).</param>
        /// <param name="itemsCount">itemsCount (required).</param>
        /// <param name="labelPrinted">labelPrinted (required).</param>
        /// <param name="orderNumber">orderNumber (required).</param>
        /// <param name="orderStatus">orderStatus (required).</param>
        /// <param name="shipmentId">shipmentId.</param>
        /// <param name="shippingAddress">shippingAddress.</param>
        /// <param name="shippingMethod">shippingMethod (required).</param>
        /// <param name="trackingNumber">trackingNumber.</param>
        /// <param name="videoRecording">videoRecording.</param>
        public PackingQueueItem(string createdAt = default, string customerId = default, bool deliveryNotePrinted = default, Object items = default, int itemsCount = default, bool labelPrinted = default, string orderNumber = default, string orderStatus = default, string shipmentId = default, Object shippingAddress = default, string shippingMethod = default, string trackingNumber = default, string videoRecording = default)
        {
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for PackingQueueItem and cannot be null");
            }
            this.CreatedAt = createdAt;
            // to ensure "customerId" is required (not null)
            if (customerId == null)
            {
                throw new ArgumentNullException("customerId is a required property for PackingQueueItem and cannot be null");
            }
            this.CustomerId = customerId;
            this.DeliveryNotePrinted = deliveryNotePrinted;
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for PackingQueueItem and cannot be null");
            }
            this.Items = items;
            this.ItemsCount = itemsCount;
            this.LabelPrinted = labelPrinted;
            // to ensure "orderNumber" is required (not null)
            if (orderNumber == null)
            {
                throw new ArgumentNullException("orderNumber is a required property for PackingQueueItem and cannot be null");
            }
            this.OrderNumber = orderNumber;
            // to ensure "orderStatus" is required (not null)
            if (orderStatus == null)
            {
                throw new ArgumentNullException("orderStatus is a required property for PackingQueueItem and cannot be null");
            }
            this.OrderStatus = orderStatus;
            // to ensure "shippingMethod" is required (not null)
            if (shippingMethod == null)
            {
                throw new ArgumentNullException("shippingMethod is a required property for PackingQueueItem and cannot be null");
            }
            this.ShippingMethod = shippingMethod;
            this.ShipmentId = shipmentId;
            this.ShippingAddress = shippingAddress;
            this.TrackingNumber = trackingNumber;
            this.VideoRecording = videoRecording;
        }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [DataMember(Name = "customer_id", IsRequired = true, EmitDefaultValue = true)]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets DeliveryNotePrinted
        /// </summary>
        [DataMember(Name = "delivery_note_printed", IsRequired = true, EmitDefaultValue = true)]
        public bool DeliveryNotePrinted { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public Object Items { get; set; }

        /// <summary>
        /// Gets or Sets ItemsCount
        /// </summary>
        [DataMember(Name = "items_count", IsRequired = true, EmitDefaultValue = true)]
        public int ItemsCount { get; set; }

        /// <summary>
        /// Gets or Sets LabelPrinted
        /// </summary>
        [DataMember(Name = "label_printed", IsRequired = true, EmitDefaultValue = true)]
        public bool LabelPrinted { get; set; }

        /// <summary>
        /// Gets or Sets OrderNumber
        /// </summary>
        [DataMember(Name = "order_number", IsRequired = true, EmitDefaultValue = true)]
        public string OrderNumber { get; set; }

        /// <summary>
        /// Gets or Sets OrderStatus
        /// </summary>
        [DataMember(Name = "order_status", IsRequired = true, EmitDefaultValue = true)]
        public string OrderStatus { get; set; }

        /// <summary>
        /// Gets or Sets ShipmentId
        /// </summary>
        [DataMember(Name = "shipment_id", EmitDefaultValue = true)]
        public string ShipmentId { get; set; }

        /// <summary>
        /// Gets or Sets ShippingAddress
        /// </summary>
        [DataMember(Name = "shipping_address", EmitDefaultValue = true)]
        public Object ShippingAddress { get; set; }

        /// <summary>
        /// Gets or Sets ShippingMethod
        /// </summary>
        [DataMember(Name = "shipping_method", IsRequired = true, EmitDefaultValue = true)]
        public string ShippingMethod { get; set; }

        /// <summary>
        /// Gets or Sets TrackingNumber
        /// </summary>
        [DataMember(Name = "tracking_number", EmitDefaultValue = true)]
        public string TrackingNumber { get; set; }

        /// <summary>
        /// Gets or Sets VideoRecording
        /// </summary>
        [DataMember(Name = "video_recording", EmitDefaultValue = true)]
        public string VideoRecording { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PackingQueueItem {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  DeliveryNotePrinted: ").Append(DeliveryNotePrinted).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  ItemsCount: ").Append(ItemsCount).Append("\n");
            sb.Append("  LabelPrinted: ").Append(LabelPrinted).Append("\n");
            sb.Append("  OrderNumber: ").Append(OrderNumber).Append("\n");
            sb.Append("  OrderStatus: ").Append(OrderStatus).Append("\n");
            sb.Append("  ShipmentId: ").Append(ShipmentId).Append("\n");
            sb.Append("  ShippingAddress: ").Append(ShippingAddress).Append("\n");
            sb.Append("  ShippingMethod: ").Append(ShippingMethod).Append("\n");
            sb.Append("  TrackingNumber: ").Append(TrackingNumber).Append("\n");
            sb.Append("  VideoRecording: ").Append(VideoRecording).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
