/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Package
    /// </summary>
    [DataContract(Name = "Package")]
    public partial class Package : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Package" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Package() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Package" /> class.
        /// </summary>
        /// <param name="description">description.</param>
        /// <param name="heightCm">heightCm.</param>
        /// <param name="lengthCm">lengthCm.</param>
        /// <param name="reference">reference.</param>
        /// <param name="weightKg">weightKg (required).</param>
        /// <param name="widthCm">widthCm.</param>
        public Package(string description = default, double? heightCm = default, double? lengthCm = default, string reference = default, double weightKg = default, double? widthCm = default)
        {
            this.WeightKg = weightKg;
            this.Description = description;
            this.HeightCm = heightCm;
            this.LengthCm = lengthCm;
            this.Reference = reference;
            this.WidthCm = widthCm;
        }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets HeightCm
        /// </summary>
        [DataMember(Name = "height_cm", EmitDefaultValue = true)]
        public double? HeightCm { get; set; }

        /// <summary>
        /// Gets or Sets LengthCm
        /// </summary>
        [DataMember(Name = "length_cm", EmitDefaultValue = true)]
        public double? LengthCm { get; set; }

        /// <summary>
        /// Gets or Sets Reference
        /// </summary>
        [DataMember(Name = "reference", EmitDefaultValue = true)]
        public string Reference { get; set; }

        /// <summary>
        /// Gets or Sets WeightKg
        /// </summary>
        [DataMember(Name = "weight_kg", IsRequired = true, EmitDefaultValue = true)]
        public double WeightKg { get; set; }

        /// <summary>
        /// Gets or Sets WidthCm
        /// </summary>
        [DataMember(Name = "width_cm", EmitDefaultValue = true)]
        public double? WidthCm { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Package {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  HeightCm: ").Append(HeightCm).Append("\n");
            sb.Append("  LengthCm: ").Append(LengthCm).Append("\n");
            sb.Append("  Reference: ").Append(Reference).Append("\n");
            sb.Append("  WeightKg: ").Append(WeightKg).Append("\n");
            sb.Append("  WidthCm: ").Append(WidthCm).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
