/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Partial feature toggles: &#x60;None&#x60; keeps the company-type default, &#x60;Some&#x60; overrides it.
    /// </summary>
    [DataContract(Name = "PartialFeatureSettings")]
    public partial class PartialFeatureSettings : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartialFeatureSettings" /> class.
        /// </summary>
        /// <param name="onlineshop">onlineshop.</param>
        /// <param name="reportBilanz">reportBilanz.</param>
        /// <param name="reportBwa">reportBwa.</param>
        /// <param name="reportEuer">reportEuer.</param>
        /// <param name="reportGewerbesteuer">reportGewerbesteuer.</param>
        /// <param name="reportGuv">reportGuv.</param>
        /// <param name="reportKst">reportKst.</param>
        /// <param name="reportUstva">reportUstva.</param>
        public PartialFeatureSettings(bool? onlineshop = default, bool? reportBilanz = default, bool? reportBwa = default, bool? reportEuer = default, bool? reportGewerbesteuer = default, bool? reportGuv = default, bool? reportKst = default, bool? reportUstva = default)
        {
            this.Onlineshop = onlineshop;
            this.ReportBilanz = reportBilanz;
            this.ReportBwa = reportBwa;
            this.ReportEuer = reportEuer;
            this.ReportGewerbesteuer = reportGewerbesteuer;
            this.ReportGuv = reportGuv;
            this.ReportKst = reportKst;
            this.ReportUstva = reportUstva;
        }

        /// <summary>
        /// Gets or Sets Onlineshop
        /// </summary>
        [DataMember(Name = "onlineshop", EmitDefaultValue = true)]
        public bool? Onlineshop { get; set; }

        /// <summary>
        /// Gets or Sets ReportBilanz
        /// </summary>
        [DataMember(Name = "reportBilanz", EmitDefaultValue = true)]
        public bool? ReportBilanz { get; set; }

        /// <summary>
        /// Gets or Sets ReportBwa
        /// </summary>
        [DataMember(Name = "reportBwa", EmitDefaultValue = true)]
        public bool? ReportBwa { get; set; }

        /// <summary>
        /// Gets or Sets ReportEuer
        /// </summary>
        [DataMember(Name = "reportEuer", EmitDefaultValue = true)]
        public bool? ReportEuer { get; set; }

        /// <summary>
        /// Gets or Sets ReportGewerbesteuer
        /// </summary>
        [DataMember(Name = "reportGewerbesteuer", EmitDefaultValue = true)]
        public bool? ReportGewerbesteuer { get; set; }

        /// <summary>
        /// Gets or Sets ReportGuv
        /// </summary>
        [DataMember(Name = "reportGuv", EmitDefaultValue = true)]
        public bool? ReportGuv { get; set; }

        /// <summary>
        /// Gets or Sets ReportKst
        /// </summary>
        [DataMember(Name = "reportKst", EmitDefaultValue = true)]
        public bool? ReportKst { get; set; }

        /// <summary>
        /// Gets or Sets ReportUstva
        /// </summary>
        [DataMember(Name = "reportUstva", EmitDefaultValue = true)]
        public bool? ReportUstva { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartialFeatureSettings {\n");
            sb.Append("  Onlineshop: ").Append(Onlineshop).Append("\n");
            sb.Append("  ReportBilanz: ").Append(ReportBilanz).Append("\n");
            sb.Append("  ReportBwa: ").Append(ReportBwa).Append("\n");
            sb.Append("  ReportEuer: ").Append(ReportEuer).Append("\n");
            sb.Append("  ReportGewerbesteuer: ").Append(ReportGewerbesteuer).Append("\n");
            sb.Append("  ReportGuv: ").Append(ReportGuv).Append("\n");
            sb.Append("  ReportKst: ").Append(ReportKst).Append("\n");
            sb.Append("  ReportUstva: ").Append(ReportUstva).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
