/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PlausibilitySummary
    /// </summary>
    [DataContract(Name = "PlausibilitySummary")]
    public partial class PlausibilitySummary : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets OverallStatus
        /// </summary>
        [DataMember(Name = "overall_status", IsRequired = true, EmitDefaultValue = true)]
        public CheckStatus OverallStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlausibilitySummary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlausibilitySummary() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlausibilitySummary" /> class.
        /// </summary>
        /// <param name="errors">errors (required).</param>
        /// <param name="overallStatus">overallStatus (required).</param>
        /// <param name="passed">passed (required).</param>
        /// <param name="totalChecks">totalChecks (required).</param>
        /// <param name="warnings">warnings (required).</param>
        public PlausibilitySummary(int errors = default, CheckStatus overallStatus = default, int passed = default, int totalChecks = default, int warnings = default)
        {
            this.Errors = errors;
            this.OverallStatus = overallStatus;
            this.Passed = passed;
            this.TotalChecks = totalChecks;
            this.Warnings = warnings;
        }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "errors", IsRequired = true, EmitDefaultValue = true)]
        public int Errors { get; set; }

        /// <summary>
        /// Gets or Sets Passed
        /// </summary>
        [DataMember(Name = "passed", IsRequired = true, EmitDefaultValue = true)]
        public int Passed { get; set; }

        /// <summary>
        /// Gets or Sets TotalChecks
        /// </summary>
        [DataMember(Name = "total_checks", IsRequired = true, EmitDefaultValue = true)]
        public int TotalChecks { get; set; }

        /// <summary>
        /// Gets or Sets Warnings
        /// </summary>
        [DataMember(Name = "warnings", IsRequired = true, EmitDefaultValue = true)]
        public int Warnings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlausibilitySummary {\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  OverallStatus: ").Append(OverallStatus).Append("\n");
            sb.Append("  Passed: ").Append(Passed).Append("\n");
            sb.Append("  TotalChecks: ").Append(TotalChecks).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Errors (int) minimum
            if (this.Errors < (int)0)
            {
                yield return new ValidationResult("Invalid value for Errors, must be a value greater than or equal to 0.", new [] { "Errors" });
            }

            // Passed (int) minimum
            if (this.Passed < (int)0)
            {
                yield return new ValidationResult("Invalid value for Passed, must be a value greater than or equal to 0.", new [] { "Passed" });
            }

            // TotalChecks (int) minimum
            if (this.TotalChecks < (int)0)
            {
                yield return new ValidationResult("Invalid value for TotalChecks, must be a value greater than or equal to 0.", new [] { "TotalChecks" });
            }

            // Warnings (int) minimum
            if (this.Warnings < (int)0)
            {
                yield return new ValidationResult("Invalid value for Warnings, must be a value greater than or equal to 0.", new [] { "Warnings" });
            }

            yield break;
        }
    }

}
