/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PriceTierCreate
    /// </summary>
    [DataContract(Name = "PriceTierCreate")]
    public partial class PriceTierCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PriceTierCreate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PriceTierCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PriceTierCreate" /> class.
        /// </summary>
        /// <param name="customerGroupId">None &#x3D; tier applies to all customers; otherwise a customer group id..</param>
        /// <param name="minQuantity">Quantity from which this tier applies (inclusive)..</param>
        /// <param name="productId">References the product entity. (required).</param>
        /// <param name="unitPrice">Net unit price once &#x60;min_quantity&#x60; is reached. (required).</param>
        public PriceTierCreate(string customerGroupId = default, long minQuantity = default, Guid productId = default, string unitPrice = default)
        {
            this.ProductId = productId;
            // to ensure "unitPrice" is required (not null)
            if (unitPrice == null)
            {
                throw new ArgumentNullException("unitPrice is a required property for PriceTierCreate and cannot be null");
            }
            this.UnitPrice = unitPrice;
            this.CustomerGroupId = customerGroupId;
            this.MinQuantity = minQuantity;
        }

        /// <summary>
        /// None &#x3D; tier applies to all customers; otherwise a customer group id.
        /// </summary>
        /// <value>None &#x3D; tier applies to all customers; otherwise a customer group id.</value>
        [DataMember(Name = "customerGroupId", EmitDefaultValue = true)]
        public string CustomerGroupId { get; set; }

        /// <summary>
        /// Quantity from which this tier applies (inclusive).
        /// </summary>
        /// <value>Quantity from which this tier applies (inclusive).</value>
        [DataMember(Name = "minQuantity", EmitDefaultValue = false)]
        public long MinQuantity { get; set; }

        /// <summary>
        /// References the product entity.
        /// </summary>
        /// <value>References the product entity.</value>
        [DataMember(Name = "productId", IsRequired = true, EmitDefaultValue = true)]
        public Guid ProductId { get; set; }

        /// <summary>
        /// Net unit price once &#x60;min_quantity&#x60; is reached.
        /// </summary>
        /// <value>Net unit price once &#x60;min_quantity&#x60; is reached.</value>
        [DataMember(Name = "unitPrice", IsRequired = true, EmitDefaultValue = true)]
        public string UnitPrice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PriceTierCreate {\n");
            sb.Append("  CustomerGroupId: ").Append(CustomerGroupId).Append("\n");
            sb.Append("  MinQuantity: ").Append(MinQuantity).Append("\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  UnitPrice: ").Append(UnitPrice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
