/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Actual-costing (Nachkalkulation) report for a production order.
    /// </summary>
    [DataContract(Name = "ProductionOrderCosting")]
    public partial class ProductionOrderCosting : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductionOrderCosting" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProductionOrderCosting() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductionOrderCosting" /> class.
        /// </summary>
        /// <param name="costPerUnit">material_cost_total ÷ quantity. (required).</param>
        /// <param name="costSource">\&quot;actual\&quot; when costed from stock-movement consumption, else \&quot;planned\&quot;. (required).</param>
        /// <param name="lines">lines (required).</param>
        /// <param name="marginPerUnit">sale_price − cost_per_unit..</param>
        /// <param name="marginPercent">margin_per_unit ÷ cost_per_unit as a percentage..</param>
        /// <param name="materialCostTotal">Total material cost for the whole order. (required).</param>
        /// <param name="orderNumber">orderNumber (required).</param>
        /// <param name="productionOrderId">productionOrderId (required).</param>
        /// <param name="quantity">quantity (required).</param>
        /// <param name="salePrice">Finished product&#39;s sale price per unit (used to compute margin)..</param>
        /// <param name="status">status (required).</param>
        public ProductionOrderCosting(string costPerUnit = default, string costSource = default, List<CostingLine> lines = default, string marginPerUnit = default, string marginPercent = default, string materialCostTotal = default, string orderNumber = default, Guid productionOrderId = default, long quantity = default, string salePrice = default, string status = default)
        {
            // to ensure "costPerUnit" is required (not null)
            if (costPerUnit == null)
            {
                throw new ArgumentNullException("costPerUnit is a required property for ProductionOrderCosting and cannot be null");
            }
            this.CostPerUnit = costPerUnit;
            // to ensure "costSource" is required (not null)
            if (costSource == null)
            {
                throw new ArgumentNullException("costSource is a required property for ProductionOrderCosting and cannot be null");
            }
            this.CostSource = costSource;
            // to ensure "lines" is required (not null)
            if (lines == null)
            {
                throw new ArgumentNullException("lines is a required property for ProductionOrderCosting and cannot be null");
            }
            this.Lines = lines;
            // to ensure "materialCostTotal" is required (not null)
            if (materialCostTotal == null)
            {
                throw new ArgumentNullException("materialCostTotal is a required property for ProductionOrderCosting and cannot be null");
            }
            this.MaterialCostTotal = materialCostTotal;
            // to ensure "orderNumber" is required (not null)
            if (orderNumber == null)
            {
                throw new ArgumentNullException("orderNumber is a required property for ProductionOrderCosting and cannot be null");
            }
            this.OrderNumber = orderNumber;
            this.ProductionOrderId = productionOrderId;
            this.Quantity = quantity;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for ProductionOrderCosting and cannot be null");
            }
            this.Status = status;
            this.MarginPerUnit = marginPerUnit;
            this.MarginPercent = marginPercent;
            this.SalePrice = salePrice;
        }

        /// <summary>
        /// material_cost_total ÷ quantity.
        /// </summary>
        /// <value>material_cost_total ÷ quantity.</value>
        [DataMember(Name = "costPerUnit", IsRequired = true, EmitDefaultValue = true)]
        public string CostPerUnit { get; set; }

        /// <summary>
        /// \&quot;actual\&quot; when costed from stock-movement consumption, else \&quot;planned\&quot;.
        /// </summary>
        /// <value>\&quot;actual\&quot; when costed from stock-movement consumption, else \&quot;planned\&quot;.</value>
        [DataMember(Name = "costSource", IsRequired = true, EmitDefaultValue = true)]
        public string CostSource { get; set; }

        /// <summary>
        /// Gets or Sets Lines
        /// </summary>
        [DataMember(Name = "lines", IsRequired = true, EmitDefaultValue = true)]
        public List<CostingLine> Lines { get; set; }

        /// <summary>
        /// sale_price − cost_per_unit.
        /// </summary>
        /// <value>sale_price − cost_per_unit.</value>
        [DataMember(Name = "marginPerUnit", EmitDefaultValue = true)]
        public string MarginPerUnit { get; set; }

        /// <summary>
        /// margin_per_unit ÷ cost_per_unit as a percentage.
        /// </summary>
        /// <value>margin_per_unit ÷ cost_per_unit as a percentage.</value>
        [DataMember(Name = "marginPercent", EmitDefaultValue = true)]
        public string MarginPercent { get; set; }

        /// <summary>
        /// Total material cost for the whole order.
        /// </summary>
        /// <value>Total material cost for the whole order.</value>
        [DataMember(Name = "materialCostTotal", IsRequired = true, EmitDefaultValue = true)]
        public string MaterialCostTotal { get; set; }

        /// <summary>
        /// Gets or Sets OrderNumber
        /// </summary>
        [DataMember(Name = "orderNumber", IsRequired = true, EmitDefaultValue = true)]
        public string OrderNumber { get; set; }

        /// <summary>
        /// Gets or Sets ProductionOrderId
        /// </summary>
        [DataMember(Name = "productionOrderId", IsRequired = true, EmitDefaultValue = true)]
        public Guid ProductionOrderId { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name = "quantity", IsRequired = true, EmitDefaultValue = true)]
        public long Quantity { get; set; }

        /// <summary>
        /// Finished product&#39;s sale price per unit (used to compute margin).
        /// </summary>
        /// <value>Finished product&#39;s sale price per unit (used to compute margin).</value>
        [DataMember(Name = "salePrice", EmitDefaultValue = true)]
        public string SalePrice { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductionOrderCosting {\n");
            sb.Append("  CostPerUnit: ").Append(CostPerUnit).Append("\n");
            sb.Append("  CostSource: ").Append(CostSource).Append("\n");
            sb.Append("  Lines: ").Append(Lines).Append("\n");
            sb.Append("  MarginPerUnit: ").Append(MarginPerUnit).Append("\n");
            sb.Append("  MarginPercent: ").Append(MarginPercent).Append("\n");
            sb.Append("  MaterialCostTotal: ").Append(MaterialCostTotal).Append("\n");
            sb.Append("  OrderNumber: ").Append(OrderNumber).Append("\n");
            sb.Append("  ProductionOrderId: ").Append(ProductionOrderId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  SalePrice: ").Append(SalePrice).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
