/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// StockAdjustment
    /// </summary>
    [DataContract(Name = "StockAdjustment")]
    public partial class StockAdjustment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StockAdjustment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StockAdjustment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StockAdjustment" /> class.
        /// </summary>
        /// <param name="batchNumber">batchNumber.</param>
        /// <param name="binLocation">binLocation.</param>
        /// <param name="expiryDate">expiryDate.</param>
        /// <param name="productId">productId.</param>
        /// <param name="quantity">quantity (required).</param>
        /// <param name="serialNumbers">serialNumbers.</param>
        public StockAdjustment(string batchNumber = default, string binLocation = default, DateOnly? expiryDate = default, Guid productId = default, long quantity = default, List<string> serialNumbers = default)
        {
            this.Quantity = quantity;
            this.BatchNumber = batchNumber;
            this.BinLocation = binLocation;
            this.ExpiryDate = expiryDate;
            this.ProductId = productId;
            this.SerialNumbers = serialNumbers;
        }

        /// <summary>
        /// Gets or Sets BatchNumber
        /// </summary>
        [DataMember(Name = "batchNumber", EmitDefaultValue = true)]
        public string BatchNumber { get; set; }

        /// <summary>
        /// Gets or Sets BinLocation
        /// </summary>
        [DataMember(Name = "binLocation", EmitDefaultValue = true)]
        public string BinLocation { get; set; }

        /// <summary>
        /// Gets or Sets ExpiryDate
        /// </summary>
        [DataMember(Name = "expiryDate", EmitDefaultValue = true)]
        public DateOnly? ExpiryDate { get; set; }

        /// <summary>
        /// Gets or Sets ProductId
        /// </summary>
        [DataMember(Name = "productId", EmitDefaultValue = false)]
        public Guid ProductId { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name = "quantity", IsRequired = true, EmitDefaultValue = true)]
        public long Quantity { get; set; }

        /// <summary>
        /// Gets or Sets SerialNumbers
        /// </summary>
        [DataMember(Name = "serialNumbers", EmitDefaultValue = true)]
        public List<string> SerialNumbers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StockAdjustment {\n");
            sb.Append("  BatchNumber: ").Append(BatchNumber).Append("\n");
            sb.Append("  BinLocation: ").Append(BinLocation).Append("\n");
            sb.Append("  ExpiryDate: ").Append(ExpiryDate).Append("\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  SerialNumbers: ").Append(SerialNumbers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
