/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TotpSetupResponse
    /// </summary>
    [DataContract(Name = "TotpSetupResponse")]
    public partial class TotpSetupResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TotpSetupResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TotpSetupResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TotpSetupResponse" /> class.
        /// </summary>
        /// <param name="backupCodes">backupCodes (required).</param>
        /// <param name="qrCodeUrl">qrCodeUrl (required).</param>
        /// <param name="secret">secret (required).</param>
        public TotpSetupResponse(List<string> backupCodes = default, string qrCodeUrl = default, string secret = default)
        {
            // to ensure "backupCodes" is required (not null)
            if (backupCodes == null)
            {
                throw new ArgumentNullException("backupCodes is a required property for TotpSetupResponse and cannot be null");
            }
            this.BackupCodes = backupCodes;
            // to ensure "qrCodeUrl" is required (not null)
            if (qrCodeUrl == null)
            {
                throw new ArgumentNullException("qrCodeUrl is a required property for TotpSetupResponse and cannot be null");
            }
            this.QrCodeUrl = qrCodeUrl;
            // to ensure "secret" is required (not null)
            if (secret == null)
            {
                throw new ArgumentNullException("secret is a required property for TotpSetupResponse and cannot be null");
            }
            this.Secret = secret;
        }

        /// <summary>
        /// Gets or Sets BackupCodes
        /// </summary>
        [DataMember(Name = "backup_codes", IsRequired = true, EmitDefaultValue = true)]
        public List<string> BackupCodes { get; set; }

        /// <summary>
        /// Gets or Sets QrCodeUrl
        /// </summary>
        [DataMember(Name = "qr_code_url", IsRequired = true, EmitDefaultValue = true)]
        public string QrCodeUrl { get; set; }

        /// <summary>
        /// Gets or Sets Secret
        /// </summary>
        [DataMember(Name = "secret", IsRequired = true, EmitDefaultValue = true)]
        public string Secret { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TotpSetupResponse {\n");
            sb.Append("  BackupCodes: ").Append(BackupCodes).Append("\n");
            sb.Append("  QrCodeUrl: ").Append(QrCodeUrl).Append("\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
