/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TrackedShipment
    /// </summary>
    [DataContract(Name = "TrackedShipment")]
    public partial class TrackedShipment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackedShipment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TrackedShipment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackedShipment" /> class.
        /// </summary>
        /// <param name="carrier">carrier (required).</param>
        /// <param name="events">events (required).</param>
        /// <param name="labelUrl">labelUrl.</param>
        /// <param name="status">status (required).</param>
        /// <param name="trackingNumber">trackingNumber.</param>
        /// <param name="trackingUrl">trackingUrl.</param>
        public TrackedShipment(string carrier = default, List<TrackingEvent> events = default, string labelUrl = default, string status = default, string trackingNumber = default, string trackingUrl = default)
        {
            // to ensure "carrier" is required (not null)
            if (carrier == null)
            {
                throw new ArgumentNullException("carrier is a required property for TrackedShipment and cannot be null");
            }
            this.Carrier = carrier;
            // to ensure "events" is required (not null)
            if (events == null)
            {
                throw new ArgumentNullException("events is a required property for TrackedShipment and cannot be null");
            }
            this.Events = events;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for TrackedShipment and cannot be null");
            }
            this.Status = status;
            this.LabelUrl = labelUrl;
            this.TrackingNumber = trackingNumber;
            this.TrackingUrl = trackingUrl;
        }

        /// <summary>
        /// Gets or Sets Carrier
        /// </summary>
        [DataMember(Name = "carrier", IsRequired = true, EmitDefaultValue = true)]
        public string Carrier { get; set; }

        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        [DataMember(Name = "events", IsRequired = true, EmitDefaultValue = true)]
        public List<TrackingEvent> Events { get; set; }

        /// <summary>
        /// Gets or Sets LabelUrl
        /// </summary>
        [DataMember(Name = "label_url", EmitDefaultValue = true)]
        public string LabelUrl { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets TrackingNumber
        /// </summary>
        [DataMember(Name = "tracking_number", EmitDefaultValue = true)]
        public string TrackingNumber { get; set; }

        /// <summary>
        /// Gets or Sets TrackingUrl
        /// </summary>
        [DataMember(Name = "tracking_url", EmitDefaultValue = true)]
        public string TrackingUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackedShipment {\n");
            sb.Append("  Carrier: ").Append(Carrier).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("  LabelUrl: ").Append(LabelUrl).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TrackingNumber: ").Append(TrackingNumber).Append("\n");
            sb.Append("  TrackingUrl: ").Append(TrackingUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
