/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// UpdateSyncDirectionRequest
    /// </summary>
    [DataContract(Name = "UpdateSyncDirectionRequest")]
    public partial class UpdateSyncDirectionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSyncDirectionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateSyncDirectionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSyncDirectionRequest" /> class.
        /// </summary>
        /// <param name="directions">directions (required).</param>
        public UpdateSyncDirectionRequest(Dictionary<string, string> directions = default)
        {
            // to ensure "directions" is required (not null)
            if (directions == null)
            {
                throw new ArgumentNullException("directions is a required property for UpdateSyncDirectionRequest and cannot be null");
            }
            this.Directions = directions;
        }

        /// <summary>
        /// Gets or Sets Directions
        /// </summary>
        [DataMember(Name = "directions", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, string> Directions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateSyncDirectionRequest {\n");
            sb.Append("  Directions: ").Append(Directions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
