/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ComplianceTrainingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ComplianceTrainingApiTests : IDisposable
    {
        private ComplianceTrainingApi instance;

        public ComplianceTrainingApiTests()
        {
            instance = new ComplianceTrainingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComplianceTrainingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ComplianceTrainingApi
            //Assert.IsType<ComplianceTrainingApi>(instance);
        }

        /// <summary>
        /// Test CreateComplianceTraining
        /// </summary>
        [Fact]
        public void CreateComplianceTrainingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComplianceTrainingCreate complianceTrainingCreate = null;
            //var response = instance.CreateComplianceTraining(complianceTrainingCreate);
            //Assert.IsType<ComplianceTraining>(response);
        }

        /// <summary>
        /// Test DeleteComplianceTraining
        /// </summary>
        [Fact]
        public void DeleteComplianceTrainingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //instance.DeleteComplianceTraining(id);
        }

        /// <summary>
        /// Test GetComplianceTraining
        /// </summary>
        [Fact]
        public void GetComplianceTrainingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetComplianceTraining(id);
            //Assert.IsType<ComplianceTraining>(response);
        }

        /// <summary>
        /// Test GetComplianceTrainings
        /// </summary>
        [Fact]
        public void GetComplianceTrainingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? pageSize = null;
            //string? search = null;
            //bool? includeDeleted = null;
            //var response = instance.GetComplianceTrainings(page, pageSize, search, includeDeleted);
            //Assert.IsType<List<ComplianceTraining>>(response);
        }

        /// <summary>
        /// Test UpdateComplianceTraining
        /// </summary>
        [Fact]
        public void UpdateComplianceTrainingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //ComplianceTrainingUpdate complianceTrainingUpdate = null;
            //var response = instance.UpdateComplianceTraining(id, complianceTrainingUpdate);
            //Assert.IsType<ComplianceTraining>(response);
        }
    }
}
