/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing CustomerCommunicationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CustomerCommunicationApiTests : IDisposable
    {
        private CustomerCommunicationApi instance;

        public CustomerCommunicationApiTests()
        {
            instance = new CustomerCommunicationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerCommunicationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CustomerCommunicationApi
            //Assert.IsType<CustomerCommunicationApi>(instance);
        }

        /// <summary>
        /// Test CreateCommunication
        /// </summary>
        [Fact]
        public void CreateCommunicationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CustomerCommunicationCreate customerCommunicationCreate = null;
            //var response = instance.CreateCommunication(customerCommunicationCreate);
            //Assert.IsType<CustomerCommunication>(response);
        }

        /// <summary>
        /// Test CustomercommunicationRestore
        /// </summary>
        [Fact]
        public void CustomercommunicationRestoreTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string communicationId = null;
            //var response = instance.CustomercommunicationRestore(communicationId);
            //Assert.IsType<CustomerCommunication>(response);
        }

        /// <summary>
        /// Test DeleteCommunication
        /// </summary>
        [Fact]
        public void DeleteCommunicationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string communicationId = null;
            //instance.DeleteCommunication(communicationId);
        }

        /// <summary>
        /// Test GetCommunication
        /// </summary>
        [Fact]
        public void GetCommunicationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string communicationId = null;
            //var response = instance.GetCommunication(communicationId);
            //Assert.IsType<CustomerCommunication>(response);
        }

        /// <summary>
        /// Test GetContactHistory
        /// </summary>
        [Fact]
        public void GetContactHistoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contactId = null;
            //var response = instance.GetContactHistory(contactId);
            //Assert.IsType<ContactHistoryResponse>(response);
        }

        /// <summary>
        /// Test ListCommunications
        /// </summary>
        [Fact]
        public void ListCommunicationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? pageSize = null;
            //string? contactId = null;
            //CommunicationChannel? channel = null;
            //CommunicationDirection? direction = null;
            //DateOnly? from = null;
            //DateOnly? to = null;
            //var response = instance.ListCommunications(page, pageSize, contactId, channel, direction, from, to);
            //Assert.IsType<List<CustomerCommunication>>(response);
        }

        /// <summary>
        /// Test UpdateCommunication
        /// </summary>
        [Fact]
        public void UpdateCommunicationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string communicationId = null;
            //CustomerCommunicationUpdate customerCommunicationUpdate = null;
            //var response = instance.UpdateCommunication(communicationId, customerCommunicationUpdate);
            //Assert.IsType<CustomerCommunication>(response);
        }
    }
}
