/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing GenerateQrcodeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GenerateQrcodeApiTests : IDisposable
    {
        private GenerateQrcodeApi instance;

        public GenerateQrcodeApiTests()
        {
            instance = new GenerateQrcodeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerateQrcodeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GenerateQrcodeApi
            //Assert.IsType<GenerateQrcodeApi>(instance);
        }

        /// <summary>
        /// Test GenerateQrcodeApi
        /// </summary>
        [Fact]
        public void GenerateQrcodeApiTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string iban = null;
            //string id = null;
            //string? holderName = null;
            //string? bic = null;
            //string? amount = null;
            //string? reference = null;
            //string? purpose = null;
            //var response = instance.GenerateQrcodeApi(iban, id, holderName, bic, amount, reference, purpose);
            //Assert.IsType<QRCodeResponse>(response);
        }
    }
}
