/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing InventoryValueApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class InventoryValueApiTests : IDisposable
    {
        private InventoryValueApi instance;

        public InventoryValueApiTests()
        {
            instance = new InventoryValueApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InventoryValueApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' InventoryValueApi
            //Assert.IsType<InventoryValueApi>(instance);
        }

        /// <summary>
        /// Test GetInventoryValueApi
        /// </summary>
        [Fact]
        public void GetInventoryValueApiTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetInventoryValueApi();
            //Assert.IsType<CurrentInventoryValue>(response);
        }

        /// <summary>
        /// Test RecordInventoryValueApi
        /// </summary>
        [Fact]
        public void RecordInventoryValueApiTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.RecordInventoryValueApi();
            //Assert.IsType<InventoryValuePoint>(response);
        }
    }
}
