/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ProductVariantApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProductVariantApiTests : IDisposable
    {
        private ProductVariantApi instance;

        public ProductVariantApiTests()
        {
            instance = new ProductVariantApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductVariantApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProductVariantApi
            //Assert.IsType<ProductVariantApi>(instance);
        }

        /// <summary>
        /// Test CreateProductVariant
        /// </summary>
        [Fact]
        public void CreateProductVariantTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductVariant productVariant = null;
            //var response = instance.CreateProductVariant(productVariant);
            //Assert.IsType<ProductVariant>(response);
        }

        /// <summary>
        /// Test DeleteProductVariant
        /// </summary>
        [Fact]
        public void DeleteProductVariantTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string variantId = null;
            //instance.DeleteProductVariant(variantId);
        }

        /// <summary>
        /// Test GenerateProductVariants
        /// </summary>
        [Fact]
        public void GenerateProductVariantsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GenerateVariantsRequest generateVariantsRequest = null;
            //var response = instance.GenerateProductVariants(generateVariantsRequest);
            //Assert.IsType<List<ProductVariant>>(response);
        }

        /// <summary>
        /// Test GetProductVariant
        /// </summary>
        [Fact]
        public void GetProductVariantTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string variantId = null;
            //var response = instance.GetProductVariant(variantId);
            //Assert.IsType<ProductVariant>(response);
        }

        /// <summary>
        /// Test ListProductVariants
        /// </summary>
        [Fact]
        public void ListProductVariantsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? pageSize = null;
            //Guid? productId = null;
            //bool? isActive = null;
            //var response = instance.ListProductVariants(page, pageSize, productId, isActive);
            //Assert.IsType<List<ProductVariant>>(response);
        }

        /// <summary>
        /// Test UpdateProductVariant
        /// </summary>
        [Fact]
        public void UpdateProductVariantTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string variantId = null;
            //Object body = null;
            //var response = instance.UpdateProductVariant(variantId, body);
            //Assert.IsType<ProductVariant>(response);
        }
    }
}
