/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ProformaInvoiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProformaInvoiceApiTests : IDisposable
    {
        private ProformaInvoiceApi instance;

        public ProformaInvoiceApiTests()
        {
            instance = new ProformaInvoiceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProformaInvoiceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProformaInvoiceApi
            //Assert.IsType<ProformaInvoiceApi>(instance);
        }

        /// <summary>
        /// Test ConvertProformaToInvoice
        /// </summary>
        [Fact]
        public void ConvertProformaToInvoiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string proformaId = null;
            //var response = instance.ConvertProformaToInvoice(proformaId);
            //Assert.IsType<ConvertResponse>(response);
        }

        /// <summary>
        /// Test CreateProformaInvoice
        /// </summary>
        [Fact]
        public void CreateProformaInvoiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProformaInvoice proformaInvoice = null;
            //var response = instance.CreateProformaInvoice(proformaInvoice);
            //Assert.IsType<ProformaInvoice>(response);
        }

        /// <summary>
        /// Test DeleteProformaInvoice
        /// </summary>
        [Fact]
        public void DeleteProformaInvoiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string proformaId = null;
            //instance.DeleteProformaInvoice(proformaId);
        }

        /// <summary>
        /// Test GetProformaInvoice
        /// </summary>
        [Fact]
        public void GetProformaInvoiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string proformaId = null;
            //var response = instance.GetProformaInvoice(proformaId);
            //Assert.IsType<ProformaInvoice>(response);
        }

        /// <summary>
        /// Test ListProformaInvoices
        /// </summary>
        [Fact]
        public void ListProformaInvoicesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? pageSize = null;
            //string? status = null;
            //string? customerId = null;
            //string? orderNumber = null;
            //var response = instance.ListProformaInvoices(page, pageSize, status, customerId, orderNumber);
            //Assert.IsType<List<ProformaInvoice>>(response);
        }

        /// <summary>
        /// Test UpdateProformaInvoice
        /// </summary>
        [Fact]
        public void UpdateProformaInvoiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string proformaId = null;
            //Object body = null;
            //var response = instance.UpdateProformaInvoice(proformaId, body);
            //Assert.IsType<ProformaInvoice>(response);
        }
    }
}
