/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ReplenishmentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ReplenishmentApiTests : IDisposable
    {
        private ReplenishmentApi instance;

        public ReplenishmentApiTests()
        {
            instance = new ReplenishmentApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReplenishmentApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ReplenishmentApi
            //Assert.IsType<ReplenishmentApi>(instance);
        }

        /// <summary>
        /// Test ApplyReplenishments
        /// </summary>
        [Fact]
        public void ApplyReplenishmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? targetWarehouseId = null;
            //string? sourceWarehouseId = null;
            //var response = instance.ApplyReplenishments(targetWarehouseId, sourceWarehouseId);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GetReplenishments
        /// </summary>
        [Fact]
        public void GetReplenishmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? targetWarehouseId = null;
            //string? sourceWarehouseId = null;
            //var response = instance.GetReplenishments(targetWarehouseId, sourceWarehouseId);
            //Assert.IsType<ReplenishmentResponse>(response);
        }
    }
}
