/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ReturnOrderApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ReturnOrderApiTests : IDisposable
    {
        private ReturnOrderApi instance;

        public ReturnOrderApiTests()
        {
            instance = new ReturnOrderApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReturnOrderApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ReturnOrderApi
            //Assert.IsType<ReturnOrderApi>(instance);
        }

        /// <summary>
        /// Test CreateReturnOrder
        /// </summary>
        [Fact]
        public void CreateReturnOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ReturnOrder returnOrder = null;
            //var response = instance.CreateReturnOrder(returnOrder);
            //Assert.IsType<ReturnOrder>(response);
        }

        /// <summary>
        /// Test DeleteReturnOrder
        /// </summary>
        [Fact]
        public void DeleteReturnOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string returnOrderId = null;
            //instance.DeleteReturnOrder(returnOrderId);
        }

        /// <summary>
        /// Test GetReturnOrder
        /// </summary>
        [Fact]
        public void GetReturnOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string returnOrderId = null;
            //var response = instance.GetReturnOrder(returnOrderId);
            //Assert.IsType<ReturnOrder>(response);
        }

        /// <summary>
        /// Test ListReturnOrders
        /// </summary>
        [Fact]
        public void ListReturnOrdersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? pageSize = null;
            //string? status = null;
            //string? customerName = null;
            //string? orderNumber = null;
            //var response = instance.ListReturnOrders(page, pageSize, status, customerName, orderNumber);
            //Assert.IsType<List<ReturnOrder>>(response);
        }

        /// <summary>
        /// Test ReturnLogisticsQueue
        /// </summary>
        [Fact]
        public void ReturnLogisticsQueueTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ReturnLogisticsQueue();
            //Assert.IsType<List<ReturnLogisticsQueueItem>>(response);
        }

        /// <summary>
        /// Test ReturnLogisticsSummary
        /// </summary>
        [Fact]
        public void ReturnLogisticsSummaryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ReturnLogisticsSummary();
            //Assert.IsType<ReturnLogisticsSummary>(response);
        }

        /// <summary>
        /// Test UpdateReturnOrder
        /// </summary>
        [Fact]
        public void UpdateReturnOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string returnOrderId = null;
            //Object body = null;
            //var response = instance.UpdateReturnOrder(returnOrderId, body);
            //Assert.IsType<ReturnOrder>(response);
        }

        /// <summary>
        /// Test UpdateReturnOrderStatus
        /// </summary>
        [Fact]
        public void UpdateReturnOrderStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string returnOrderId = null;
            //ReturnOrderStatusUpdate returnOrderStatusUpdate = null;
            //var response = instance.UpdateReturnOrderStatus(returnOrderId, returnOrderStatusUpdate);
            //Assert.IsType<ReturnOrder>(response);
        }
    }
}
