/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing TrainingsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TrainingsApiTests : IDisposable
    {
        private TrainingsApi instance;

        public TrainingsApiTests()
        {
            instance = new TrainingsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrainingsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TrainingsApi
            //Assert.IsType<TrainingsApi>(instance);
        }

        /// <summary>
        /// Test GetMyTrainings
        /// </summary>
        [Fact]
        public void GetMyTrainingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetMyTrainings();
            //Assert.IsType<List<MyTrainingItem>>(response);
        }

        /// <summary>
        /// Test GetTrainingContent
        /// </summary>
        [Fact]
        public void GetTrainingContentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string code = null;
            //var response = instance.GetTrainingContent(code);
            //Assert.IsType<TrainingContent>(response);
        }

        /// <summary>
        /// Test GetTrainingOverview
        /// </summary>
        [Fact]
        public void GetTrainingOverviewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetTrainingOverview();
            //Assert.IsType<List<HrTrainingOverview>>(response);
        }

        /// <summary>
        /// Test SubmitTrainingResult
        /// </summary>
        [Fact]
        public void SubmitTrainingResultTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SubmitResultDto submitResultDto = null;
            //var response = instance.SubmitTrainingResult(submitResultDto);
            //Assert.IsType<SubmitResultResponse>(response);
        }
    }
}
