/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing WarehouseStockApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WarehouseStockApiTests : IDisposable
    {
        private WarehouseStockApi instance;

        public WarehouseStockApiTests()
        {
            instance = new WarehouseStockApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WarehouseStockApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' WarehouseStockApi
            //Assert.IsType<WarehouseStockApi>(instance);
        }

        /// <summary>
        /// Test CreateWarehouseStock
        /// </summary>
        [Fact]
        public void CreateWarehouseStockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string warehouseId = null;
            //StockAdjustment stockAdjustment = null;
            //var response = instance.CreateWarehouseStock(warehouseId, stockAdjustment);
            //Assert.IsType<WarehouseStock>(response);
        }

        /// <summary>
        /// Test DeleteWarehouseStock
        /// </summary>
        [Fact]
        public void DeleteWarehouseStockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string warehouseId = null;
            //Guid productId = null;
            //instance.DeleteWarehouseStock(warehouseId, productId);
        }

        /// <summary>
        /// Test ListWarehouseStock
        /// </summary>
        [Fact]
        public void ListWarehouseStockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string warehouseId = null;
            //var response = instance.ListWarehouseStock(warehouseId);
            //Assert.IsType<List<WarehouseStock>>(response);
        }

        /// <summary>
        /// Test UpdateWarehouseStock
        /// </summary>
        [Fact]
        public void UpdateWarehouseStockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string warehouseId = null;
            //Guid productId = null;
            //StockAdjustment stockAdjustment = null;
            //var response = instance.UpdateWarehouseStock(warehouseId, productId, stockAdjustment);
            //Assert.IsType<WarehouseStock>(response);
        }
    }
}
