/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AutomationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AutomationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AutomationDto
        //private AutomationDto instance;

        public AutomationDtoTests()
        {
            // TODO uncomment below to create an instance of AutomationDto
            //instance = new AutomationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AutomationDto
        /// </summary>
        [Fact]
        public void AutomationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AutomationDto
            //Assert.IsType<AutomationDto>(instance);
        }

        /// <summary>
        /// Test the property 'AutomationKey'
        /// </summary>
        [Fact]
        public void AutomationKeyTest()
        {
            // TODO unit test for the property 'AutomationKey'
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }

        /// <summary>
        /// Test the property 'DefaultDay'
        /// </summary>
        [Fact]
        public void DefaultDayTest()
        {
            // TODO unit test for the property 'DefaultDay'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Fact]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }

        /// <summary>
        /// Test the property 'LastRunAt'
        /// </summary>
        [Fact]
        public void LastRunAtTest()
        {
            // TODO unit test for the property 'LastRunAt'
        }

        /// <summary>
        /// Test the property 'NextRunAt'
        /// </summary>
        [Fact]
        public void NextRunAtTest()
        {
            // TODO unit test for the property 'NextRunAt'
        }

        /// <summary>
        /// Test the property 'ScheduleKind'
        /// </summary>
        [Fact]
        public void ScheduleKindTest()
        {
            // TODO unit test for the property 'ScheduleKind'
        }
    }
}
