/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ContactUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContactUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContactUpdate
        //private ContactUpdate instance;

        public ContactUpdateTests()
        {
            // TODO uncomment below to create an instance of ContactUpdate
            //instance = new ContactUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContactUpdate
        /// </summary>
        [Fact]
        public void ContactUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContactUpdate
            //Assert.IsType<ContactUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'AccountHolder'
        /// </summary>
        [Fact]
        public void AccountHolderTest()
        {
            // TODO unit test for the property 'AccountHolder'
        }

        /// <summary>
        /// Test the property 'AcquisitionCost'
        /// </summary>
        [Fact]
        public void AcquisitionCostTest()
        {
            // TODO unit test for the property 'AcquisitionCost'
        }

        /// <summary>
        /// Test the property 'AddressSupplement'
        /// </summary>
        [Fact]
        public void AddressSupplementTest()
        {
            // TODO unit test for the property 'AddressSupplement'
        }

        /// <summary>
        /// Test the property 'Attention'
        /// </summary>
        [Fact]
        public void AttentionTest()
        {
            // TODO unit test for the property 'Attention'
        }

        /// <summary>
        /// Test the property 'BankName'
        /// </summary>
        [Fact]
        public void BankNameTest()
        {
            // TODO unit test for the property 'BankName'
        }

        /// <summary>
        /// Test the property 'Bic'
        /// </summary>
        [Fact]
        public void BicTest()
        {
            // TODO unit test for the property 'Bic'
        }

        /// <summary>
        /// Test the property 'BuyerReference'
        /// </summary>
        [Fact]
        public void BuyerReferenceTest()
        {
            // TODO unit test for the property 'BuyerReference'
        }

        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

        /// <summary>
        /// Test the property 'CertificateAuthority'
        /// </summary>
        [Fact]
        public void CertificateAuthorityTest()
        {
            // TODO unit test for the property 'CertificateAuthority'
        }

        /// <summary>
        /// Test the property 'CertificateNumber'
        /// </summary>
        [Fact]
        public void CertificateNumberTest()
        {
            // TODO unit test for the property 'CertificateNumber'
        }

        /// <summary>
        /// Test the property 'CertificateParagraph'
        /// </summary>
        [Fact]
        public void CertificateParagraphTest()
        {
            // TODO unit test for the property 'CertificateParagraph'
        }

        /// <summary>
        /// Test the property 'CertificateValidUntil'
        /// </summary>
        [Fact]
        public void CertificateValidUntilTest()
        {
            // TODO unit test for the property 'CertificateValidUntil'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }

        /// <summary>
        /// Test the property 'ContactPersons'
        /// </summary>
        [Fact]
        public void ContactPersonsTest()
        {
            // TODO unit test for the property 'ContactPersons'
        }

        /// <summary>
        /// Test the property 'ContactType'
        /// </summary>
        [Fact]
        public void ContactTypeTest()
        {
            // TODO unit test for the property 'ContactType'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'CreditLimit'
        /// </summary>
        [Fact]
        public void CreditLimitTest()
        {
            // TODO unit test for the property 'CreditLimit'
        }

        /// <summary>
        /// Test the property 'CreditorAccountSkr03'
        /// </summary>
        [Fact]
        public void CreditorAccountSkr03Test()
        {
            // TODO unit test for the property 'CreditorAccountSkr03'
        }

        /// <summary>
        /// Test the property 'CreditorAccountSkr04'
        /// </summary>
        [Fact]
        public void CreditorAccountSkr04Test()
        {
            // TODO unit test for the property 'CreditorAccountSkr04'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }

        /// <summary>
        /// Test the property 'CustomerNumber'
        /// </summary>
        [Fact]
        public void CustomerNumberTest()
        {
            // TODO unit test for the property 'CustomerNumber'
        }

        /// <summary>
        /// Test the property 'DebitorAccountSkr03'
        /// </summary>
        [Fact]
        public void DebitorAccountSkr03Test()
        {
            // TODO unit test for the property 'DebitorAccountSkr03'
        }

        /// <summary>
        /// Test the property 'DebitorAccountSkr04'
        /// </summary>
        [Fact]
        public void DebitorAccountSkr04Test()
        {
            // TODO unit test for the property 'DebitorAccountSkr04'
        }

        /// <summary>
        /// Test the property 'DefaultDebitorNumber'
        /// </summary>
        [Fact]
        public void DefaultDebitorNumberTest()
        {
            // TODO unit test for the property 'DefaultDebitorNumber'
        }

        /// <summary>
        /// Test the property 'DeliveryBlock'
        /// </summary>
        [Fact]
        public void DeliveryBlockTest()
        {
            // TODO unit test for the property 'DeliveryBlock'
        }

        /// <summary>
        /// Test the property 'Department'
        /// </summary>
        [Fact]
        public void DepartmentTest()
        {
            // TODO unit test for the property 'Department'
        }

        /// <summary>
        /// Test the property 'DiscountDays'
        /// </summary>
        [Fact]
        public void DiscountDaysTest()
        {
            // TODO unit test for the property 'DiscountDays'
        }

        /// <summary>
        /// Test the property 'DiscountPercentage'
        /// </summary>
        [Fact]
        public void DiscountPercentageTest()
        {
            // TODO unit test for the property 'DiscountPercentage'
        }

        /// <summary>
        /// Test the property 'DonationReceiptEligible'
        /// </summary>
        [Fact]
        public void DonationReceiptEligibleTest()
        {
            // TODO unit test for the property 'DonationReceiptEligible'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }

        /// <summary>
        /// Test the property 'Fax'
        /// </summary>
        [Fact]
        public void FaxTest()
        {
            // TODO unit test for the property 'Fax'
        }

        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Fact]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }

        /// <summary>
        /// Test the property 'Industry'
        /// </summary>
        [Fact]
        public void IndustryTest()
        {
            // TODO unit test for the property 'Industry'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'IsMember'
        /// </summary>
        [Fact]
        public void IsMemberTest()
        {
            // TODO unit test for the property 'IsMember'
        }

        /// <summary>
        /// Test the property 'IsNonprofit'
        /// </summary>
        [Fact]
        public void IsNonprofitTest()
        {
            // TODO unit test for the property 'IsNonprofit'
        }

        /// <summary>
        /// Test the property 'LastContactDate'
        /// </summary>
        [Fact]
        public void LastContactDateTest()
        {
            // TODO unit test for the property 'LastContactDate'
        }

        /// <summary>
        /// Test the property 'LastPurchaseDate'
        /// </summary>
        [Fact]
        public void LastPurchaseDateTest()
        {
            // TODO unit test for the property 'LastPurchaseDate'
        }

        /// <summary>
        /// Test the property 'LeitwegId'
        /// </summary>
        [Fact]
        public void LeitwegIdTest()
        {
            // TODO unit test for the property 'LeitwegId'
        }

        /// <summary>
        /// Test the property 'LifetimeValue'
        /// </summary>
        [Fact]
        public void LifetimeValueTest()
        {
            // TODO unit test for the property 'LifetimeValue'
        }

        /// <summary>
        /// Test the property 'MandateDate'
        /// </summary>
        [Fact]
        public void MandateDateTest()
        {
            // TODO unit test for the property 'MandateDate'
        }

        /// <summary>
        /// Test the property 'MandateReference'
        /// </summary>
        [Fact]
        public void MandateReferenceTest()
        {
            // TODO unit test for the property 'MandateReference'
        }

        /// <summary>
        /// Test the property 'MarketingConsent'
        /// </summary>
        [Fact]
        public void MarketingConsentTest()
        {
            // TODO unit test for the property 'MarketingConsent'
        }

        /// <summary>
        /// Test the property 'MarketingConsentAt'
        /// </summary>
        [Fact]
        public void MarketingConsentAtTest()
        {
            // TODO unit test for the property 'MarketingConsentAt'
        }

        /// <summary>
        /// Test the property 'MarketingConsentSource'
        /// </summary>
        [Fact]
        public void MarketingConsentSourceTest()
        {
            // TODO unit test for the property 'MarketingConsentSource'
        }

        /// <summary>
        /// Test the property 'Mobile'
        /// </summary>
        [Fact]
        public void MobileTest()
        {
            // TODO unit test for the property 'Mobile'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'NextContactDate'
        /// </summary>
        [Fact]
        public void NextContactDateTest()
        {
            // TODO unit test for the property 'NextContactDate'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'OpeningBalance'
        /// </summary>
        [Fact]
        public void OpeningBalanceTest()
        {
            // TODO unit test for the property 'OpeningBalance'
        }

        /// <summary>
        /// Test the property 'OpeningBalanceDate'
        /// </summary>
        [Fact]
        public void OpeningBalanceDateTest()
        {
            // TODO unit test for the property 'OpeningBalanceDate'
        }

        /// <summary>
        /// Test the property 'OrderReference'
        /// </summary>
        [Fact]
        public void OrderReferenceTest()
        {
            // TODO unit test for the property 'OrderReference'
        }

        /// <summary>
        /// Test the property 'PaymentBlock'
        /// </summary>
        [Fact]
        public void PaymentBlockTest()
        {
            // TODO unit test for the property 'PaymentBlock'
        }

        /// <summary>
        /// Test the property 'PaymentGracePeriodDays'
        /// </summary>
        [Fact]
        public void PaymentGracePeriodDaysTest()
        {
            // TODO unit test for the property 'PaymentGracePeriodDays'
        }

        /// <summary>
        /// Test the property 'PaymentMethods'
        /// </summary>
        [Fact]
        public void PaymentMethodsTest()
        {
            // TODO unit test for the property 'PaymentMethods'
        }

        /// <summary>
        /// Test the property 'PaymentTerms'
        /// </summary>
        [Fact]
        public void PaymentTermsTest()
        {
            // TODO unit test for the property 'PaymentTerms'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Rating'
        /// </summary>
        [Fact]
        public void RatingTest()
        {
            // TODO unit test for the property 'Rating'
        }

        /// <summary>
        /// Test the property 'SalesRepresentative'
        /// </summary>
        [Fact]
        public void SalesRepresentativeTest()
        {
            // TODO unit test for the property 'SalesRepresentative'
        }

        /// <summary>
        /// Test the property 'SepaBatchBooking'
        /// </summary>
        [Fact]
        public void SepaBatchBookingTest()
        {
            // TODO unit test for the property 'SepaBatchBooking'
        }

        /// <summary>
        /// Test the property 'SepaSequenceType'
        /// </summary>
        [Fact]
        public void SepaSequenceTypeTest()
        {
            // TODO unit test for the property 'SepaSequenceType'
        }

        /// <summary>
        /// Test the property 'SocialMedia'
        /// </summary>
        [Fact]
        public void SocialMediaTest()
        {
            // TODO unit test for the property 'SocialMedia'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Fact]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }

        /// <summary>
        /// Test the property 'StreetNumber'
        /// </summary>
        [Fact]
        public void StreetNumberTest()
        {
            // TODO unit test for the property 'StreetNumber'
        }

        /// <summary>
        /// Test the property 'SupplierNumber'
        /// </summary>
        [Fact]
        public void SupplierNumberTest()
        {
            // TODO unit test for the property 'SupplierNumber'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'TaxCountry'
        /// </summary>
        [Fact]
        public void TaxCountryTest()
        {
            // TODO unit test for the property 'TaxCountry'
        }

        /// <summary>
        /// Test the property 'TaxNumber'
        /// </summary>
        [Fact]
        public void TaxNumberTest()
        {
            // TODO unit test for the property 'TaxNumber'
        }

        /// <summary>
        /// Test the property 'TaxOffice'
        /// </summary>
        [Fact]
        public void TaxOfficeTest()
        {
            // TODO unit test for the property 'TaxOffice'
        }

        /// <summary>
        /// Test the property 'TotalInvoices'
        /// </summary>
        [Fact]
        public void TotalInvoicesTest()
        {
            // TODO unit test for the property 'TotalInvoices'
        }

        /// <summary>
        /// Test the property 'TotalRevenue'
        /// </summary>
        [Fact]
        public void TotalRevenueTest()
        {
            // TODO unit test for the property 'TotalRevenue'
        }

        /// <summary>
        /// Test the property 'VatId'
        /// </summary>
        [Fact]
        public void VatIdTest()
        {
            // TODO unit test for the property 'VatId'
        }

        /// <summary>
        /// Test the property 'VatIdValidated'
        /// </summary>
        [Fact]
        public void VatIdValidatedTest()
        {
            // TODO unit test for the property 'VatIdValidated'
        }

        /// <summary>
        /// Test the property 'VatIdValidationDate'
        /// </summary>
        [Fact]
        public void VatIdValidationDateTest()
        {
            // TODO unit test for the property 'VatIdValidationDate'
        }

        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }

        /// <summary>
        /// Test the property 'Zip'
        /// </summary>
        [Fact]
        public void ZipTest()
        {
            // TODO unit test for the property 'Zip'
        }
    }
}
