/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing EmissionEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmissionEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmissionEntry
        //private EmissionEntry instance;

        public EmissionEntryTests()
        {
            // TODO uncomment below to create an instance of EmissionEntry
            //instance = new EmissionEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmissionEntry
        /// </summary>
        [Fact]
        public void EmissionEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmissionEntry
            //Assert.IsType<EmissionEntry>(instance);
        }

        /// <summary>
        /// Test the property 'ActivityValue'
        /// </summary>
        [Fact]
        public void ActivityValueTest()
        {
            // TODO unit test for the property 'ActivityValue'
        }

        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Fact]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'EfSource'
        /// </summary>
        [Fact]
        public void EfSourceTest()
        {
            // TODO unit test for the property 'EfSource'
        }

        /// <summary>
        /// Test the property 'EfVersion'
        /// </summary>
        [Fact]
        public void EfVersionTest()
        {
            // TODO unit test for the property 'EfVersion'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }

        /// <summary>
        /// Test the property 'Tco2e'
        /// </summary>
        [Fact]
        public void Tco2eTest()
        {
            // TODO unit test for the property 'Tco2e'
        }

        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
    }
}
