/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FeatureSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeatureSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FeatureSettings
        //private FeatureSettings instance;

        public FeatureSettingsTests()
        {
            // TODO uncomment below to create an instance of FeatureSettings
            //instance = new FeatureSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeatureSettings
        /// </summary>
        [Fact]
        public void FeatureSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" FeatureSettings
            //Assert.IsType<FeatureSettings>(instance);
        }

        /// <summary>
        /// Test the property 'Onlineshop'
        /// </summary>
        [Fact]
        public void OnlineshopTest()
        {
            // TODO unit test for the property 'Onlineshop'
        }

        /// <summary>
        /// Test the property 'ReportBilanz'
        /// </summary>
        [Fact]
        public void ReportBilanzTest()
        {
            // TODO unit test for the property 'ReportBilanz'
        }

        /// <summary>
        /// Test the property 'ReportBwa'
        /// </summary>
        [Fact]
        public void ReportBwaTest()
        {
            // TODO unit test for the property 'ReportBwa'
        }

        /// <summary>
        /// Test the property 'ReportEuer'
        /// </summary>
        [Fact]
        public void ReportEuerTest()
        {
            // TODO unit test for the property 'ReportEuer'
        }

        /// <summary>
        /// Test the property 'ReportGewerbesteuer'
        /// </summary>
        [Fact]
        public void ReportGewerbesteuerTest()
        {
            // TODO unit test for the property 'ReportGewerbesteuer'
        }

        /// <summary>
        /// Test the property 'ReportGuv'
        /// </summary>
        [Fact]
        public void ReportGuvTest()
        {
            // TODO unit test for the property 'ReportGuv'
        }

        /// <summary>
        /// Test the property 'ReportKst'
        /// </summary>
        [Fact]
        public void ReportKstTest()
        {
            // TODO unit test for the property 'ReportKst'
        }

        /// <summary>
        /// Test the property 'ReportUstva'
        /// </summary>
        [Fact]
        public void ReportUstvaTest()
        {
            // TODO unit test for the property 'ReportUstva'
        }
    }
}
