/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FristEintrag
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FristEintragTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FristEintrag
        //private FristEintrag instance;

        public FristEintragTests()
        {
            // TODO uncomment below to create an instance of FristEintrag
            //instance = new FristEintrag();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FristEintrag
        /// </summary>
        [Fact]
        public void FristEintragInstanceTest()
        {
            // TODO uncomment below to test "IsType" FristEintrag
            //Assert.IsType<FristEintrag>(instance);
        }

        /// <summary>
        /// Test the property 'Bezeichnung'
        /// </summary>
        [Fact]
        public void BezeichnungTest()
        {
            // TODO unit test for the property 'Bezeichnung'
        }

        /// <summary>
        /// Test the property 'Faellig'
        /// </summary>
        [Fact]
        public void FaelligTest()
        {
            // TODO unit test for the property 'Faellig'
        }

        /// <summary>
        /// Test the property 'FaelligOriginal'
        /// </summary>
        [Fact]
        public void FaelligOriginalTest()
        {
            // TODO unit test for the property 'FaelligOriginal'
        }

        /// <summary>
        /// Test the property 'Hinweis'
        /// </summary>
        [Fact]
        public void HinweisTest()
        {
            // TODO unit test for the property 'Hinweis'
        }

        /// <summary>
        /// Test the property 'Typ'
        /// </summary>
        [Fact]
        public void TypTest()
        {
            // TODO unit test for the property 'Typ'
        }

        /// <summary>
        /// Test the property 'Zeitraum'
        /// </summary>
        [Fact]
        public void ZeitraumTest()
        {
            // TODO unit test for the property 'Zeitraum'
        }
    }
}
