/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GatewayOAuthCallbackRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GatewayOAuthCallbackRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GatewayOAuthCallbackRequest
        //private GatewayOAuthCallbackRequest instance;

        public GatewayOAuthCallbackRequestTests()
        {
            // TODO uncomment below to create an instance of GatewayOAuthCallbackRequest
            //instance = new GatewayOAuthCallbackRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GatewayOAuthCallbackRequest
        /// </summary>
        [Fact]
        public void GatewayOAuthCallbackRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GatewayOAuthCallbackRequest
            //Assert.IsType<GatewayOAuthCallbackRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'GatewayType'
        /// </summary>
        [Fact]
        public void GatewayTypeTest()
        {
            // TODO unit test for the property 'GatewayType'
        }

        /// <summary>
        /// Test the property 'RedirectUri'
        /// </summary>
        [Fact]
        public void RedirectUriTest()
        {
            // TODO unit test for the property 'RedirectUri'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
    }
}
