/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GroupFigure
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupFigureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GroupFigure
        //private GroupFigure instance;

        public GroupFigureTests()
        {
            // TODO uncomment below to create an instance of GroupFigure
            //instance = new GroupFigure();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupFigure
        /// </summary>
        [Fact]
        public void GroupFigureInstanceTest()
        {
            // TODO uncomment below to test "IsType" GroupFigure
            //Assert.IsType<GroupFigure>(instance);
        }

        /// <summary>
        /// Test the property 'Bilanzsumme'
        /// </summary>
        [Fact]
        public void BilanzsummeTest()
        {
            // TODO unit test for the property 'Bilanzsumme'
        }

        /// <summary>
        /// Test the property 'ExemptionClaimed'
        /// </summary>
        [Fact]
        public void ExemptionClaimedTest()
        {
            // TODO unit test for the property 'ExemptionClaimed'
        }

        /// <summary>
        /// Test the property 'Mitarbeiter'
        /// </summary>
        [Fact]
        public void MitarbeiterTest()
        {
            // TODO unit test for the property 'Mitarbeiter'
        }

        /// <summary>
        /// Test the property 'NettoUmsatz'
        /// </summary>
        [Fact]
        public void NettoUmsatzTest()
        {
            // TODO unit test for the property 'NettoUmsatz'
        }

        /// <summary>
        /// Test the property 'ParentName'
        /// </summary>
        [Fact]
        public void ParentNameTest()
        {
            // TODO unit test for the property 'ParentName'
        }

        /// <summary>
        /// Test the property 'ParentSitus'
        /// </summary>
        [Fact]
        public void ParentSitusTest()
        {
            // TODO unit test for the property 'ParentSitus'
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
    }
}
