/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing KonzernBeteiligung
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KonzernBeteiligungTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KonzernBeteiligung
        //private KonzernBeteiligung instance;

        public KonzernBeteiligungTests()
        {
            // TODO uncomment below to create an instance of KonzernBeteiligung
            //instance = new KonzernBeteiligung();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KonzernBeteiligung
        /// </summary>
        [Fact]
        public void KonzernBeteiligungInstanceTest()
        {
            // TODO uncomment below to test "IsType" KonzernBeteiligung
            //Assert.IsType<KonzernBeteiligung>(instance);
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }

        /// <summary>
        /// Test the property 'ControlBasis'
        /// </summary>
        [Fact]
        public void ControlBasisTest()
        {
            // TODO unit test for the property 'ControlBasis'
        }

        /// <summary>
        /// Test the property 'Controlled'
        /// </summary>
        [Fact]
        public void ControlledTest()
        {
            // TODO unit test for the property 'Controlled'
        }

        /// <summary>
        /// Test the property 'OwnershipPct'
        /// </summary>
        [Fact]
        public void OwnershipPctTest()
        {
            // TODO unit test for the property 'OwnershipPct'
        }
    }
}
