/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MarketplaceConnection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MarketplaceConnectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MarketplaceConnection
        //private MarketplaceConnection instance;

        public MarketplaceConnectionTests()
        {
            // TODO uncomment below to create an instance of MarketplaceConnection
            //instance = new MarketplaceConnection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MarketplaceConnection
        /// </summary>
        [Fact]
        public void MarketplaceConnectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" MarketplaceConnection
            //Assert.IsType<MarketplaceConnection>(instance);
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }

        /// <summary>
        /// Test the property 'ConnectionId'
        /// </summary>
        [Fact]
        public void ConnectionIdTest()
        {
            // TODO unit test for the property 'ConnectionId'
        }

        /// <summary>
        /// Test the property 'ConnectorType'
        /// </summary>
        [Fact]
        public void ConnectorTypeTest()
        {
            // TODO unit test for the property 'ConnectorType'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'LastSyncAt'
        /// </summary>
        [Fact]
        public void LastSyncAtTest()
        {
            // TODO unit test for the property 'LastSyncAt'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'PlatformUserId'
        /// </summary>
        [Fact]
        public void PlatformUserIdTest()
        {
            // TODO unit test for the property 'PlatformUserId'
        }

        /// <summary>
        /// Test the property 'Scopes'
        /// </summary>
        [Fact]
        public void ScopesTest()
        {
            // TODO unit test for the property 'Scopes'
        }

        /// <summary>
        /// Test the property 'ShopDomain'
        /// </summary>
        [Fact]
        public void ShopDomainTest()
        {
            // TODO unit test for the property 'ShopDomain'
        }

        /// <summary>
        /// Test the property 'ShopName'
        /// </summary>
        [Fact]
        public void ShopNameTest()
        {
            // TODO unit test for the property 'ShopName'
        }

        /// <summary>
        /// Test the property 'SyncStatus'
        /// </summary>
        [Fact]
        public void SyncStatusTest()
        {
            // TODO unit test for the property 'SyncStatus'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
