/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MyTrainingItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MyTrainingItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MyTrainingItem
        //private MyTrainingItem instance;

        public MyTrainingItemTests()
        {
            // TODO uncomment below to create an instance of MyTrainingItem
            //instance = new MyTrainingItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MyTrainingItem
        /// </summary>
        [Fact]
        public void MyTrainingItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" MyTrainingItem
            //Assert.IsType<MyTrainingItem>(instance);
        }

        /// <summary>
        /// Test the property 'AssignmentId'
        /// </summary>
        [Fact]
        public void AssignmentIdTest()
        {
            // TODO unit test for the property 'AssignmentId'
        }

        /// <summary>
        /// Test the property 'CertificateId'
        /// </summary>
        [Fact]
        public void CertificateIdTest()
        {
            // TODO unit test for the property 'CertificateId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }

        /// <summary>
        /// Test the property 'LastScore'
        /// </summary>
        [Fact]
        public void LastScoreTest()
        {
            // TODO unit test for the property 'LastScore'
        }

        /// <summary>
        /// Test the property 'PassScore'
        /// </summary>
        [Fact]
        public void PassScoreTest()
        {
            // TODO unit test for the property 'PassScore'
        }

        /// <summary>
        /// Test the property 'Passed'
        /// </summary>
        [Fact]
        public void PassedTest()
        {
            // TODO unit test for the property 'Passed'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'TrainingId'
        /// </summary>
        [Fact]
        public void TrainingIdTest()
        {
            // TODO unit test for the property 'TrainingId'
        }

        /// <summary>
        /// Test the property 'ValidUntil'
        /// </summary>
        [Fact]
        public void ValidUntilTest()
        {
            // TODO unit test for the property 'ValidUntil'
        }
    }
}
