/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentConditionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentCondition
        //private PaymentCondition instance;

        public PaymentConditionTests()
        {
            // TODO uncomment below to create an instance of PaymentCondition
            //instance = new PaymentCondition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentCondition
        /// </summary>
        [Fact]
        public void PaymentConditionInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentCondition
            //Assert.IsType<PaymentCondition>(instance);
        }

        /// <summary>
        /// Test the property 'DiscountDays'
        /// </summary>
        [Fact]
        public void DiscountDaysTest()
        {
            // TODO unit test for the property 'DiscountDays'
        }

        /// <summary>
        /// Test the property 'DiscountPercentage'
        /// </summary>
        [Fact]
        public void DiscountPercentageTest()
        {
            // TODO unit test for the property 'DiscountPercentage'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'PaymentTermDays'
        /// </summary>
        [Fact]
        public void PaymentTermDaysTest()
        {
            // TODO unit test for the property 'PaymentTermDays'
        }
    }
}
