/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PayrollAutopayPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayrollAutopayPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PayrollAutopayPayload
        //private PayrollAutopayPayload instance;

        public PayrollAutopayPayloadTests()
        {
            // TODO uncomment below to create an instance of PayrollAutopayPayload
            //instance = new PayrollAutopayPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PayrollAutopayPayload
        /// </summary>
        [Fact]
        public void PayrollAutopayPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" PayrollAutopayPayload
            //Assert.IsType<PayrollAutopayPayload>(instance);
        }

        /// <summary>
        /// Test the property 'DebtorBic'
        /// </summary>
        [Fact]
        public void DebtorBicTest()
        {
            // TODO unit test for the property 'DebtorBic'
        }

        /// <summary>
        /// Test the property 'DebtorIban'
        /// </summary>
        [Fact]
        public void DebtorIbanTest()
        {
            // TODO unit test for the property 'DebtorIban'
        }

        /// <summary>
        /// Test the property 'DebtorName'
        /// </summary>
        [Fact]
        public void DebtorNameTest()
        {
            // TODO unit test for the property 'DebtorName'
        }

        /// <summary>
        /// Test the property 'ExecutionDate'
        /// </summary>
        [Fact]
        public void ExecutionDateTest()
        {
            // TODO unit test for the property 'ExecutionDate'
        }
    }
}
