/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing QRCodeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QRCodeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QRCodeResponse
        //private QRCodeResponse instance;

        public QRCodeResponseTests()
        {
            // TODO uncomment below to create an instance of QRCodeResponse
            //instance = new QRCodeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QRCodeResponse
        /// </summary>
        [Fact]
        public void QRCodeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" QRCodeResponse
            //Assert.IsType<QRCodeResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Fact]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }

        /// <summary>
        /// Test the property 'QrCodeBase64'
        /// </summary>
        [Fact]
        public void QrCodeBase64Test()
        {
            // TODO unit test for the property 'QrCodeBase64'
        }
    }
}
