/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing QuotationCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuotationCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuotationCreate
        //private QuotationCreate instance;

        public QuotationCreateTests()
        {
            // TODO uncomment below to create an instance of QuotationCreate
            //instance = new QuotationCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuotationCreate
        /// </summary>
        [Fact]
        public void QuotationCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuotationCreate
            //Assert.IsType<QuotationCreate>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'ContactId'
        /// </summary>
        [Fact]
        public void ContactIdTest()
        {
            // TODO unit test for the property 'ContactId'
        }

        /// <summary>
        /// Test the property 'ContactName'
        /// </summary>
        [Fact]
        public void ContactNameTest()
        {
            // TODO unit test for the property 'ContactName'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Fact]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }

        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Fact]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }

        /// <summary>
        /// Test the property 'Introduction'
        /// </summary>
        [Fact]
        public void IntroductionTest()
        {
            // TODO unit test for the property 'Introduction'
        }

        /// <summary>
        /// Test the property 'LineItems'
        /// </summary>
        [Fact]
        public void LineItemsTest()
        {
            // TODO unit test for the property 'LineItems'
        }

        /// <summary>
        /// Test the property 'PrecedingSalesVoucherId'
        /// </summary>
        [Fact]
        public void PrecedingSalesVoucherIdTest()
        {
            // TODO unit test for the property 'PrecedingSalesVoucherId'
        }

        /// <summary>
        /// Test the property 'PrecedingSalesVoucherType'
        /// </summary>
        [Fact]
        public void PrecedingSalesVoucherTypeTest()
        {
            // TODO unit test for the property 'PrecedingSalesVoucherType'
        }

        /// <summary>
        /// Test the property 'QuotationNumber'
        /// </summary>
        [Fact]
        public void QuotationNumberTest()
        {
            // TODO unit test for the property 'QuotationNumber'
        }

        /// <summary>
        /// Test the property 'Remark'
        /// </summary>
        [Fact]
        public void RemarkTest()
        {
            // TODO unit test for the property 'Remark'
        }

        /// <summary>
        /// Test the property 'TaxCondition'
        /// </summary>
        [Fact]
        public void TaxConditionTest()
        {
            // TODO unit test for the property 'TaxCondition'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'VoucherDate'
        /// </summary>
        [Fact]
        public void VoucherDateTest()
        {
            // TODO unit test for the property 'VoucherDate'
        }

        /// <summary>
        /// Test the property 'VoucherStatus'
        /// </summary>
        [Fact]
        public void VoucherStatusTest()
        {
            // TODO unit test for the property 'VoucherStatus'
        }
    }
}
