/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ReorderProposalLine
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReorderProposalLineTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReorderProposalLine
        //private ReorderProposalLine instance;

        public ReorderProposalLineTests()
        {
            // TODO uncomment below to create an instance of ReorderProposalLine
            //instance = new ReorderProposalLine();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReorderProposalLine
        /// </summary>
        [Fact]
        public void ReorderProposalLineInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReorderProposalLine
            //Assert.IsType<ReorderProposalLine>(instance);
        }

        /// <summary>
        /// Test the property 'CurrentStock'
        /// </summary>
        [Fact]
        public void CurrentStockTest()
        {
            // TODO unit test for the property 'CurrentStock'
        }

        /// <summary>
        /// Test the property 'MaxStock'
        /// </summary>
        [Fact]
        public void MaxStockTest()
        {
            // TODO unit test for the property 'MaxStock'
        }

        /// <summary>
        /// Test the property 'MinStock'
        /// </summary>
        [Fact]
        public void MinStockTest()
        {
            // TODO unit test for the property 'MinStock'
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Fact]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }

        /// <summary>
        /// Test the property 'ReorderQuantity'
        /// </summary>
        [Fact]
        public void ReorderQuantityTest()
        {
            // TODO unit test for the property 'ReorderQuantity'
        }

        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Fact]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }

        /// <summary>
        /// Test the property 'SuggestedQuantity'
        /// </summary>
        [Fact]
        public void SuggestedQuantityTest()
        {
            // TODO unit test for the property 'SuggestedQuantity'
        }
    }
}
