/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceAssignment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceAssignmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceAssignment
        //private ServiceAssignment instance;

        public ServiceAssignmentTests()
        {
            // TODO uncomment below to create an instance of ServiceAssignment
            //instance = new ServiceAssignment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceAssignment
        /// </summary>
        [Fact]
        public void ServiceAssignmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceAssignment
            //Assert.IsType<ServiceAssignment>(instance);
        }

        /// <summary>
        /// Test the property 'EmployeeId'
        /// </summary>
        [Fact]
        public void EmployeeIdTest()
        {
            // TODO unit test for the property 'EmployeeId'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'ScheduledDate'
        /// </summary>
        [Fact]
        public void ScheduledDateTest()
        {
            // TODO unit test for the property 'ScheduledDate'
        }

        /// <summary>
        /// Test the property 'ScheduledEnd'
        /// </summary>
        [Fact]
        public void ScheduledEndTest()
        {
            // TODO unit test for the property 'ScheduledEnd'
        }

        /// <summary>
        /// Test the property 'ScheduledStart'
        /// </summary>
        [Fact]
        public void ScheduledStartTest()
        {
            // TODO unit test for the property 'ScheduledStart'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
