/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing StockMovement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StockMovementTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StockMovement
        //private StockMovement instance;

        public StockMovementTests()
        {
            // TODO uncomment below to create an instance of StockMovement
            //instance = new StockMovement();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StockMovement
        /// </summary>
        [Fact]
        public void StockMovementInstanceTest()
        {
            // TODO uncomment below to test "IsType" StockMovement
            //Assert.IsType<StockMovement>(instance);
        }

        /// <summary>
        /// Test the property 'Delta'
        /// </summary>
        [Fact]
        public void DeltaTest()
        {
            // TODO unit test for the property 'Delta'
        }

        /// <summary>
        /// Test the property 'MovementType'
        /// </summary>
        [Fact]
        public void MovementTypeTest()
        {
            // TODO unit test for the property 'MovementType'
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'ReferenceId'
        /// </summary>
        [Fact]
        public void ReferenceIdTest()
        {
            // TODO unit test for the property 'ReferenceId'
        }

        /// <summary>
        /// Test the property 'ReferenceType'
        /// </summary>
        [Fact]
        public void ReferenceTypeTest()
        {
            // TODO unit test for the property 'ReferenceType'
        }

        /// <summary>
        /// Test the property 'WarehouseId'
        /// </summary>
        [Fact]
        public void WarehouseIdTest()
        {
            // TODO unit test for the property 'WarehouseId'
        }
    }
}
