/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TargetProgress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TargetProgressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TargetProgress
        //private TargetProgress instance;

        public TargetProgressTests()
        {
            // TODO uncomment below to create an instance of TargetProgress
            //instance = new TargetProgress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TargetProgress
        /// </summary>
        [Fact]
        public void TargetProgressInstanceTest()
        {
            // TODO uncomment below to test "IsType" TargetProgress
            //Assert.IsType<TargetProgress>(instance);
        }

        /// <summary>
        /// Test the property 'BaseValue'
        /// </summary>
        [Fact]
        public void BaseValueTest()
        {
            // TODO unit test for the property 'BaseValue'
        }

        /// <summary>
        /// Test the property 'BaseYear'
        /// </summary>
        [Fact]
        public void BaseYearTest()
        {
            // TODO unit test for the property 'BaseYear'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ProgressPct'
        /// </summary>
        [Fact]
        public void ProgressPctTest()
        {
            // TODO unit test for the property 'ProgressPct'
        }

        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }

        /// <summary>
        /// Test the property 'TargetValue'
        /// </summary>
        [Fact]
        public void TargetValueTest()
        {
            // TODO unit test for the property 'TargetValue'
        }

        /// <summary>
        /// Test the property 'TargetYear'
        /// </summary>
        [Fact]
        public void TargetYearTest()
        {
            // TODO unit test for the property 'TargetYear'
        }
    }
}
